### ISSUE TITLE
Keine Benachrichtigung

### ISSUE THREAD

**Issue by Koberer33** [androidseb25/iGotify-Notification-Assistent#10]
Hallo,

Erstmal Danke für die Umsetzung der App.
Mein Problem ist nur ich bekomme die Mitteilungen, aber mein iPhone macht absolut keinen Mucks ... kein Banner, keinen Ton.

Danke
LG und schöne Feiertage noch

**Comment by androidseb25** [comment]
Welche API Version vom Container ist installiert?

Die aktuelle ist 1.0.0.9, vielleicht hilft es schon.

**Comment by Koberer33** [comment]
Danke für die schnelle Antwort ... ich bin jetzt alles zum 20igsten mal durchgegangen und dürfte den Fehler gefunden haben ... der Token war falsch ...
Danke nochmal 

ja und die API Version passte

**Comment by androidseb25** [comment]
Ok alles klar
