### ISSUE TITLE
[BUG] SSL Certificate expired

### ISSUE THREAD

**Issue by ArthurZangCN** [androidseb25/iGotify-Notification-Assistent#101]
After using it for a week, I suddenly received an error message today, and then I couldn't receive any push notifications. Gottify is good for viewing push messages in the app and web pages, but I can't receive notifications on my phone. Deleting the container and creating a new one is also not possible.![image](https://github.com/user-attachments/assets/7bbb1ee9-43aa-4ec6-9eef-8dabfd7d0fe2)
![image](https://github.com/user-attachments/assets/75c24877-1630-4f62-8da8-70e4c174adae)![image](https://github.com/user-attachments/assets/1e6d6c32-3b35-4192-a888-3255340702fd)

**Comment by androidseb25** [comment]
I will fix it's my Webpage SSL Certificate

**Comment by ArthurZangCN** [comment]
> I will fix it's my Webpage SSL Certificate 

How long does it take? And how can I restore it before repairing it?

**Comment by androidseb25** [comment]
It should work now

**Comment by ArthurZangCN** [comment]
> It should work now

so cool
