### ISSUE TITLE
[BUG] Missing notification time on iOS

### ISSUE THREAD

**Issue by MajorTomDE** [androidseb25/iGotify-Notification-Assistent#102]
Hello,

since a few iOS app updates I have the issue that no notification time (e.g. 2 hours ago) is displayed. I see always „vor 0s“ in all notifications and applications.

Within Gotify all is fine.

- iPhone 16 Pro
- iOS 18.0.1
- App Version 1.4.1

![IMG_4742](https://github.com/user-attachments/assets/963a64a0-bb4e-4523-89b6-501ef46fe95d)

![IMG_4740](https://github.com/user-attachments/assets/5e1a5b82-f3d5-4829-9dbb-f5d7f2b91ba1)

![IMG_4741](https://github.com/user-attachments/assets/4047d192-dcdd-446b-95af-1bebec9dfc30)

**Comment by MajorTomDE** [comment]
I checked it. ENV Variable "TZ = Europe/Berlin" is available.
The courious thing: When I click on the message details, I see the message time. 

![image](https://github.com/user-attachments/assets/67b25d49-2fe0-44c8-ab0c-a38d674b483f)

**Comment by MacGulliver** [comment]
Same for me, also have the TZ env set.
Also: Web version of Gotify shows the correct time span.

I was using NginxProxyManager before (when it was showing the correct time), could be something related the reverse Proxy?

iOS18 (was the same on iOS17)
App 1.4.1 (27)
Gotify 2.5.0
HAProxy on PFSense

**Comment by MajorTomDE** [comment]
I use also NginxProxyManager

**Comment by androidseb25** [comment]
it can be, i don't exclude it.

But i had this issue only when the environment variable for the TZ is set, that's the reason i removed it from the environment set.

Gotify has also a strange datetime format that i need to parse (yyyy-MM-dd'T'HH:mm:ss.SSSSSSSSS'Z'), before i had to struggle much more with each timezone.

**Comment by ghimele** [comment]
Hello, I have the same issue but I don't have the TZ configured.

**Comment by androidseb25** [comment]
Can someone give me some configuration informations that i can reproduce this  problem?

system / how deploy system service or docker compose / environmentvariables (no Password or something ;) ) 

and @MajorTomDE can you send me via Discord a payload from the iGotifya container?

it looks something like that

```
Message converted: {"id":9282,"appid":7,"message":"This is an message send over Gotify.","title":"Notification","priority":7,"date":"2024-10-14T11:12:39.588706706Z"}
```

**Comment by ghimele** [comment]
This is my config I use inside Unraid. I'm planning to move everything in k8s but I don't know if I can do this week.

services:
  igotify:
    container_name: igotify
    hostname: igotify
    image: ghcr.io/androidseb25/igotify-notification-assist:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    pull_policy: always
    networks:
      - net
    ports:
      - "8681:8080"
    volumes:
      - api-data:/app/data

networks:
  net:

volumes:
  api-dawwta:

**Comment by androidseb25** [comment]
and there is the problem `... I use inside Unraid ...`.
the template what is under unraid is not from me and i don't use unraid so i can't help

**Comment by androidseb25** [comment]
maybe this hint is helping from an other 0s issue where someone also use unraid

https://github.com/androidseb25/iGotify-Notification-Assistent/issues/90#issuecomment-2323512231

**Comment by MacGulliver** [comment]
using Docker on a plain Linux Host,

after removing the TZ env the Timestamp is back again as expected.

So for me, RTFM Changelog Error on my end while upgrading.
Thanks for your Time

**Comment by ogossiaux** [comment]
I got the same issue on Synology. After removed the TZ variable it was working properly! Thanks.

**Comment by MajorTomDE** [comment]
I can confirm the solution: Removing the TZ variable from gotify and gotify-notification container solves the issue.
