### ISSUE TITLE
[BUG] Unable to use iOS App anymore 

### ISSUE THREAD

**Issue by juliusmlr** [androidseb25/iGotify-Notification-Assistent#103]
Die iOS App (1.4.1) fordert ein Notification Assistent Update auf > 1.3.0.0. Ich nutze die latest version des Docker Containers und habe auch eine neuinstallation sowohl der App als auch des assistant services versucht, trotzdem komme ich nie über diesen Screen hinaus. 

Was kann ich tun? 

![IMG_7078](https://github.com/user-attachments/assets/959058ca-8c2f-4016-9913-169a694579cc)
![IMG_7079](https://github.com/user-attachments/assets/88f48b1f-becd-4e5b-948b-1dc87086c22a)

**Comment by androidseb25** [comment]
Kannst du mal schauen was unter deiner iGotify Adresse (https://igotify.domain.tld/index.html) unter dem Punkt im Bild steht?

![Bildschirmfoto 2024-10-14 um 17 15 41](https://github.com/user-attachments/assets/425c859d-408d-4e09-8b84-116aa2c3766a)

**Comment by juliusmlr** [comment]
Hi, 
danke für die schnelle Hilfe! 
Ich hatte einen Fehler in meinen Portweiterleitungen. 

Wenn es Dir hilft: 
In der App hatte ich für iGotify die selben Angeben wie für Gotify gemacht, das hatte bei der Einrichtung funktioniert. 
Ob es in der neuen Version immer noch funktioniert weiß ich nicht. 


Davon abgesehen, vielen Dank das Du dir die Mühe machst die App zu entwickeln!

**Comment by androidseb25** [comment]
Ok alles klar und kein Problem :)
