### ISSUE TITLE
[BUG] result: Fehler beim hinzugefügen des Gerätes!

### ISSUE THREAD

**Issue by Kiter1988** [androidseb25/iGotify-Notification-Assistent#106]
**Describe the bug**
Ich habe versucht per Webhook, Meldungen von meiner Synology zu iGotify zu senden.
Leider kommt immer der selbe Fehler. siehe Log unten
Ich habe bereits verschiedene Token und web urls  probiert.

web url: http://IP.33/message
HTTP-Methode POST

HTTP-Header:
Content-Type: application/json
X-Gotify-Key: "Token"

HTTP-Text:
```
{
"message": "@@TEXT@@",
"title": "Synology",
"priority": 5,
"extras": {
"client::display": {
"contentType": "text/markdown"
}
}
}
```

Log:

**Additional context**
```
10:21:44.034 INFO Logger.init():26 - ♻️ - Initialize iGotify Logger

10:21:44.083 VERBOSE AppDelegate.application():56 - APNs token retrieved: 32 bytes

10:21:44.087 VERBOSE AppDelegate.application():59 - The token: C5E0C*****D62CD

10:21:44.092 INFO SecNtfy.setApnsToken():136 - C5E0C*****D62CD

10:21:45.762 INFO SecNtfy.PostDevice():166 - ♻️ - Device already added NTFY-DEVICE-ufnXHH8r0TilY8e2SYeAffcbJf3PCEJOkC9wGspoCEMTmjju1dnuc

10:21:45.770 VERBOSE Functions.sendTokenToSecNtfy():232 - registration token: NTFY-DEVICE-ufnXHH8r0TilY8e2SYeAffcbJf3PCEJOkC9wGspoCEMTmjju1dnuc

10:21:45.778 VERBOSE Functions.sendTokenToSecNtfy():242 - result: Fehler beim hinzugefügen des Gerätes! Successful: false Token: NTFY-DEVICE-ufnXHH8r0TilY8e2SYeAffcbJf3PCEJOkC9wGspoCEMTmjju1dnuc
```

**Comment by androidseb25** [comment]
Hi der Log ist korrekt, darüber steht das das gerät bereits hinzugefügt wurde.
Und der Fehler Resultiert daraus, das es kein Success gibt, ist aber irrelavant für dein problem.

dein Post Body ist falsch.

Schau mal in meinem anderen Projekt (https://github.com/androidseb25/SSLChecker/blob/8a0d6e435bd3dcb416474685ccdd2a02765fad91/Jobs/SSLCheckerJob.cs#L124) 
 dort siehst du wie der Payload aussehen muss

**Comment by Kiter1988** [comment]
Ich komme mit dem Code leider nicht klar, bzw. hab ich's glaube ich so gemacht wie beschrieben. 
Bekomme es nicht zum Laufen. 

Token wurde eingefügt. 

Hier mal Screenshots meiner Config
![Bildschirmfoto 2024-10-17 um 14 52 01](https://github.com/user-attachments/assets/b58dd0fc-761b-4663-a678-edc67bd96f1a)
![Bildschirmfoto 2024-10-17 um 14 51 28](https://github.com/user-attachments/assets/3629ee60-f564-4934-9226-e8a7e7090f21)

**Comment by androidseb25** [comment]
Das Token ist auch korrekt? Das muss das Application Token sein von der App in Gotify zb. heißt die App DiskStation oder so.

Hast du es mal via Terminal probiert?
einfach mal ein curl machen.

`curl "http://<IP>/message?token=<APP_TOKEN>" -F "title=Message" -F "message=You see here the Message of my Gotify" -F "priority=5";`

nicht das dein Gotify von deiner Diskstation aus nicht erreichbar ist.

**Comment by Kiter1988** [comment]
Ist erreichbar, per ioBroker gehts auch schon länger und der Terminal Befehl funktioniert auch.

**Comment by androidseb25** [comment]
mmh komisch, vielleicht kommt die DiskStation nicht mit dem Webhook bzw. PayLoad klar.

Ich kann das jetzt nicht testen da ich kein NAS besitze :/

**Comment by Kiter1988** [comment]
Wenn ich das Terminal von meinem Rechner verwende wird der curl Befehl ausgeführt, auf der Syno hingegen wird der Fehler angezeigt. 
`curl: (7) Failed to connect to 192.168.178.33 port 80 after 3007 ms: Error`

Ich werde mal gucken ob ich darüber was finde.

**Comment by androidseb25** [comment]
Hast du es hinbekommen? Wenn ja kannst du die Lösung posten und den Issue schließen?

**Comment by Kiter1988** [comment]
Ich habe es hinbekommen.
Gotify ist bei mir in einem Docker Container mit macvlan auf einer Syno. 
Der DockerHost hat keine Verbindung zum Container aufbauen können (Docker geschuldet). 
Dieses bekommt man mit einer Netzwerkbrücke hin. 
Hier wird es erklärt
`https://www.youtube.com/watch?v=jCPIUDpqcgw&t=1s`
