### ISSUE TITLE
[BUG] Incorrect port

### ISSUE THREAD

**Issue by TasyDevilsky** [androidseb25/iGotify-Notification-Assistent#107]
**Describe the bug**
There is misconfiguration in Dockerfile, where is:
```
EXPOSE 5047
EXPOSE 7221
```
because of this it will never listen on port `8080`

**Expected behavior**
So it should be there also `EXPOSE 8080` or Documentation is wrong (docker-compose.yml)

**Screenshots**
Dockerfile
![Screenshot From 2024-10-24 09-36-23](https://github.com/user-attachments/assets/b5b5732a-126e-4efd-a118-c224d682e202)

Docker-Compose in `README.md`
![Screenshot From 2024-10-24 09-49-32](https://github.com/user-attachments/assets/54c8fd8e-5aa7-488c-b2b9-d12345341c7b)

**Comment by androidseb25** [comment]
It will, because .net is creating a new expose to port 8080 in the docker file by default.
