### ISSUE TITLE
[BUG] iPhone App requires notification Assistant >1.3.0.0

### ISSUE THREAD

**Issue by astern1** [androidseb25/iGotify-Notification-Assistent#108]
**Describe the bug**
Since the latest App update to 1.4.1 on 08.10.2024 iGotify is requiring notification assistant >1.3.0.0
But since 1.3.0.0 is the latest version, this check can only fail

**Expected behavior**
Require latest available version (aka >=1.3.0.0)

**Screenshots**
![iGotify_error](https://github.com/user-attachments/assets/f39b6ba9-f86d-4f24-8834-d92fd7b426fc)

**Smartphone (please complete the following information):**
 - Device: iPhone13
 - OS: 18.0.1
 - Version of Container: 1.3.0.0
 - Version of iGotify: 1.4.1 

I read already in the Appstore a comment from @androidseb25 stating that on the website there should be a solution available but couldn't find any.
So thanks a lot for helping me out.

**Comment by astern1** [comment]
Some additional info which might be helpful:

Notifications are still pushed. So I see them on my mobile at the lockscreen, I just can't open the app then.

Notification Assistant API is accessible from mobile and Version can be read
![iGotify_error_2](https://github.com/user-attachments/assets/08e73650-cc89-4ec0-adc4-8b590b6d0f82)

I run iGotify as Dockercontainer and deployed them again without success

**Comment by androidseb25** [comment]
Hi is you're docker compose up to date?

Did you try a reinstall?

In the most cases the reinstall helps.

I really don't know why the app has problems with that behavior now 🤔

I didn't change anything 😅

**Comment by astern1** [comment]
For me also very strange and honestly speaking I'm 90% sure the error is on my side...

Docker is 27.3.1
Docker Compose version is v2.29.7

so this should be fine.
So far I only tried recreating the Gotify and iGotify containers but not yet giving up :-)

Thanks a lot for your help and the effort in general!

**Comment by zandhaas** [comment]
For me restarting the IGotify container solved the issue.
