### ISSUE TITLE
Keine Push Notifications

### ISSUE THREAD

**Issue by akordowski** [androidseb25/iGotify-Notification-Assistent#11]
Erstmal herzlichen Dank für das Projekt! Leider scheitere ich daran es so zu konfigurieren, dass die Push Notifications ankommen. Habe bereits die Issues #5 & #10 gesehen, aber leider hat es mir nicht weiter geholfen.

Hier die Basis Infos:

- Gotify Version: 2.4.0
- API Server Version: 1.0.0.10
- App-Version: 1.0.5 (13)

## docker compose

```
version: "3.8"
services:
  gotify:
    container_name: gotify
    image: gotify/server-arm64
    ports:
      - 8680:80
    environment:
      - GOTIFY_DEFAULTUSER_PASS=*****
      - TZ=Europe/Berlin
    volumes:
      - ./data:/app/data
    restart: unless-stopped

  igotify:
    container_name: igotify
    image: ghcr.io/androidseb25/igotify-notification-assist:latest
    pull_policy: always
    ports:
      - 8681:8080
    environment:
      - IGOTIFY_CLIENT_TOKEN="*****"  # Der in Gotify erstellte Client Token
      - GOTIFY_SERVER_URL="http://192.168.x.x:8680"
    volumes:
      - ./igotify-data:/app/data
    restart: unless-stopped
```

Mit der Angabe `GOTIFY_SERVER_URL="http://gotify"` funktioniert es leider auch nicht.

## iGotify Container Log

```
File is created.
Client - Token: *****
Gotify - Url: ws://192.168.x.x:8680/stream?token=*****
Client connecting...Done!
Reconnection happened, type: Initial
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://[::]:8080
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /app
warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
      Failed to determine the https port for redirect.
TOKEN: d-jK5MU8*****
DEVICE: iPhone
Message received: {"id":1,"appid":1,"message":"das ist eine Testnachricht von einem curl Aufruf","title":"Das ist ein Test","priority":1,"date":"2023-12-28T15:53:18.275121169+01:00"}
Message converted: {"id":1,"appid":1,"message":"das ist eine Testnachricht von einem curl Aufruf","title":"Das ist ein Test","priority":1,"date":"2023-12-28T15:53:18.275121169+01:00"}
```

---

Ich habe den Befehl `curl "http://192.168.x.x:8680/message?token=APP_TOKEN" -F "title=Das ist ein Test" -F "message=das ist eine Testnachricht von einem curl Aufruf" -F "priority=1";` 3 mal ausgeführt, er taucht jedoch nur ein mal in dem Log auf.

Die URLs sind im DNS freigeschaltet, funktioniert leider auch nicht, wenn das DNS blocking komplett aus ist.

In der App bin ich mit dem Admin User angemeldet. Die Nachrichten werden angezeigt, aber leider kommt keine Push Notofication an. Leider bin ich mit meinem Latein am Ende. Vieleicht hast Du einen Tipp? Vielen Dank im Voraus!

**Comment by androidseb25** [comment]
führe mal bitte `nano /var/lib/docker/volumes/gotify-stack_igotify-notification-data/_data/igotify-token.txt`, schau ob dort dein token drin ist, falls ja Logge dich mal in der App aus und lösche dann die Datei mit `rm -rf /var/lib/docker/volumes/gotify-stack_igotify-notification-data/_data/igotify-token.txt`, zudem löscht du bitte mal den client und richtest die App neu ein, falls dies immernoch nicht funktioniert.
Das muss funktionieren `GOTIFY_SERVER_URL="http://gotify"` dann ist deine Konfiguration mit den tokens nicht korrekt da der Name `gotify` der DNS Name im Docker ist!

**Comment by akordowski** [comment]
Vielen Dank für die Antwort. Ich habe heute alles komplett zurück gesetzt.

- Die Container, Images und App gelöscht und alles neu aufgesetzt.
- Die `GOTIFY_SERVER_URL="http://gotify"` entsprechend angepasst.
- Der `IGOTIFY_CLIENT_TOKEN` ist der im Bereich `Gotify > Clients` erstellte Token.
- Die URLs werden vom DNS Blocker nicht blockiert.
- In der `igotify-token.txt` Datei ist der Token da.

Und denoch bekomme ich keine einzige Push Notification. Die Logs geben auch keine weiteren Anhaltspunkte. Eine Idee was ich noch versuchen könnte?

**Comment by androidseb25** [comment]
und mit dem curl kommt auch nichts an?
Hast du dich mit dem richtigen User angemeldet der auch den Client aus dem Container hat?

**Comment by akordowski** [comment]
Weder die Message gesendet über CURL noch über die Gotify API kommt als Push Notification an. Ich habe nur den `admin` Benutzer, unter dem ich den Client Token erstellt habe und mit dem ich mich auch in der App angemeldet habe.

**Comment by androidseb25** [comment]
schick mir mal den log bitte

**Comment by akordowski** [comment]
Das ist das Log aus dem `iGotify` Container.

```
File is created.
Client - Token: CknmEuR7ImD71He
Gotify - Url: ws://gotify/stream?token=CknmEuR7ImD71He
Client connecting...Done!
Reconnection happened, type: Initial
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://[::]:8080
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /app
warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
      Failed to determine the https port for redirect.
TOKEN: dQduv-lnk0lzuUnCBqMqfq:APA91bG7IblXqp-XxkDQ3YeUx4LFyoiFu-uY6lApEjhzUHzwHH2uA0bLBA5fjCl_jK5vC0Mz4YauTE9ApE-k941YV96IaJFBd-_EFQ0VdncAtkZZmYRCMQrA9pqHwnTdOLzXGZXydELm
DEVICE: iPhone
Message converted: {"id":1,"appid":1,"message":"Test Notification Message","title":"Test","priority":1,"date":"2023-12-29T20:00:45.800499944+01:00"}
Disconnection happened, type: Websocket.Client.DisconnectionInfo
Reconnection happened, type: NoMessageReceived
Disconnection happened, type: Websocket.Client.DisconnectionInfo
Reconnection happened, type: NoMessageReceived
Disconnection happened, type: Websocket.Client.DisconnectionInfo
Reconnection happened, type: NoMessageReceived
Delete Token: dQduv-lnk0lzuUnCBqMqfq:APA91bG7IblXqp-XxkDQ3YeUx4LFyoiFu-uY6lApEjhzUHzwHH2uA0bLBA5fjCl_jK5vC0Mz4YauTE9ApE-k941YV96IaJFBd-_EFQ0VdncAtkZZmYRCMQrA9pqHwnTdOLzXGZXydELm
```

**Comment by androidseb25** [comment]
mmmh sieht alles gut aus nur das er ja das Token gelöscht hat. Ansonsten sollte alles funktionieren...
Vllt blockt der DNS Blocker ja ne URL die ich noch nicht kenne

**Comment by akordowski** [comment]
> mmmh sieht alles gut aus nur das er ja das Token gelöscht hat.
Der gelöschte Token kommt daher, da ich mich in der App abgemeldet habe.

> Vllt blockt der DNS Blocker ja ne URL die ich noch nicht kenne
Ich bekomme auch keine Push Notification, wenn ich den DNS Blocker ausschalte. Deshalb kann ich das mir auch nicht erklären.

Ich werde es nochmal mit einem anderen User und einen neuen Client Token versuchen. Vielleicht bringt das was.

**Comment by akordowski** [comment]
Ich habe das Problem gefunden, die Push Notifications kommen an!

Das Problem war, dass mein DNS Blocker die URL `oauth2.googleapis.com.fritz.box` aufgelöst hat. Nachdem ich die Konfiguration des DNS Blockers angepasst habe funktioniert es wie erwartet. Vielen Dank für die Unterstüzung und sorry für die Umstände!
