### ISSUE TITLE
Abmelden zeigt dauerhaft den Progress Spinner an

### ISSUE THREAD

**Issue by akordowski** [androidseb25/iGotify-Notification-Assistent#12]
Mir ist aufgefallen, dass beim Abmelden in der iOS iGotify App (Version 1.0.5) der Progress Spinner dauerhaft angezeigt wird. Die App muss beendet und neu gestartet werden.

**Comment by androidseb25** [comment]
Danke für die info, steht schon auf der Liste

**Comment by androidseb25** [comment]
Ist mit dem Release der Version 1.1 gefixed
