### ISSUE TITLE
igotify app closes clicking on notification

### ISSUE THREAD

**Issue by lucafolin** [androidseb25/iGotify-Notification-Assistent#13]
Gotify server is working fine on docker composer on nas and igotify is working on ios 17.1.2. The problem is that when I receive a notification on ios and I try to click on it the app close itselfs and tou cannot see the notification contents.

![IMAGE-1](https://github.com/androidseb25/iGotify-Notification-Assistent/assets/9470145/bdb87e60-b493-44ed-b623-caaa3e57cc6f)

**Comment by androidseb25** [comment]
Maybe it is the iGotify notification assistant version, please upgrade to 1.0.0.12 and try again.

**Comment by lucafolin** [comment]
I have updated iGotify notification assistant to version 1.0.0.12 but the issue is still there. Please take a look ate the video.

https://github.com/androidseb25/iGotify-Notification-Assistent/assets/9470145/f681eb0d-a93f-42a9-9bd7-8a1c7b719a1e


![Screenshot 2023-12-30 (13 37 30)](https://github.com/androidseb25/iGotify-Notification-Assistent/assets/9470145/2624a293-e95b-415f-b213-566ac1f24bbc)

**Comment by androidseb25** [comment]
Ok I found now a crashlog I will fix it with the next release.

**Comment by androidseb25** [comment]
Is fixed in Version 1.1

**Comment by lucafolin** [comment]
OK thanks I will try, when will the new version 1.1 be available on the App Store?

**Comment by androidseb25** [comment]
I will inform every user via Push Notification :)

**Comment by lucafolin** [comment]
Hi with the new gotify app version :

![WhatsApp Image 2024-01-28 at 15 15 27](https://github.com/androidseb25/iGotify-Notification-Assistent/assets/9470145/d6814f02-e811-40b2-bb6a-ffbdd0a2a554)

I have the same issue with ios app.....no new notification allert ... I need to manually refresh my app !

**Comment by androidseb25** [comment]
Please write me a message with the latest log informations to igotify@sebastianrank.de
then i can look why you can't get messages and i can introduce further steps.

**Comment by lucafolin** [comment]
I'm sorry, it's my fault!
The client was not aligned with the new token. The IOS app now works!
