### ISSUE TITLE
Binary für Linux Installation?

### ISSUE THREAD

**Issue by nicedevil007** [androidseb25/iGotify-Notification-Assistent#15]
Hallo, zunächst vielen Dank für diese Lösung!

Ich habe ne Proxmox Umgebung, bei der ich fast alles auf LXC Container aufgebaut habe, machts einfach schöner mit dem Backup und Restore im Falle des Falles. Den Umweg über Docker versuche ich gerade so oft es geht zu umgehen, weshalb ich auch gotify selbst schon in einem Alma Linux laufen habe.

Wäre es möglich ne Binary zur Verfügung zustellen für deinen Dienst die wir dann mit nem Systemd restarten können etc.

Grüße und noch nen gesundes neues :)

**Comment by androidseb25** [comment]
Hi ja das wird es mit dem nächsten Großen Release geben da kann sich jeder die Daten ziehen und es sich selber builden (1.1). Nur dauert es noch eine Weile da die Verschlüsselung unter iOS Probleme macht.

**Comment by nicedevil007** [comment]
perfekt! freu mich drauf, solange muss der docker herhalten :)
der buymekaltesgetränk fehlt hier im github :) habs mal über iphone getan!

mach weiter so

**Comment by androidseb25** [comment]
Danke 🙏🏼 

Ich geb mir Mühe das ich es schnell hinbekomme

**Comment by androidseb25** [comment]
Mit dem nächsten Release bzw. Update von 1.1.0 auf 1.1.x wird es Binaries geben unter Releases.
Eine Anleitung wird es dann im Wiki geben

**Comment by doubleugm** [comment]
Perfekt. Vielen dank !

**Comment by androidseb25** [comment]
Binaries sind nun verfügbar!

https://github.com/androidseb25/iGotify-Notification-Assistent/releases

Anleitung findet ihr im Wiki:
https://github.com/androidseb25/iGotify-Notification-Assistent/wiki/Installation-%E2%80%90-Service

**Comment by androidseb25** [comment]
Bitte gebt mir mal bescheid ob es funktioniert hat.

**Comment by nicedevil007** [comment]
Heute eher Feierabend, teste nachher im LXC 😎

**Comment by androidseb25** [comment]
> Heute eher Feierabend, teste nachher im LXC 😎

ok vllt behebt eine neuinstallation des iGotify Assistenten ja das problem im anderen Issue

**Comment by nicedevil007** [comment]
haste mir nen tipp wie ich deine 4 arguments mit dem CLI befehl reingeben könnte?
also mal beispiel, was ich getestet habe und net klappt:

```bash
/root/.dotnet/dotnet '/opt/iGotify/iGotify Notification Assist.dll' --property:IGOTIFY_CLIENT_TOKEN=TOKEN_CLIENT_GOTIFY --property:GOTIFY_SERVER_URL="https://URL_DES_GOTIFY_SERVERS" --property:ASPNETCORE_URLS="http://0.0.0.0
:8681" --property:ASPNETCORE_ENVIRONMENT=Production
```

**Comment by androidseb25** [comment]
Versuche mal fogendes, sitze gerade nicht am PC um es zu testen.


`IGOTIFY_CLIENT_TOKEN=TOKEN_CLIENT_GOTIFY GOTIFY_SERVER_URL="https://URL_DES_GOTIFY_SERVERS" ASPNETCORE_URLS="http://0.0.0.0:8681" ASPNETCORE_ENVIRONMENT=Production /root/.dotnet/dotnet '/opt/iGotify/iGotify Notification Assist.dll' `

**Comment by nicedevil007** [comment]
> Versuche mal fogendes, sitze gerade nicht am PC um es zu testen.
> 
> `IGOTIFY_CLIENT_TOKEN=TOKEN_CLIENT_GOTIFY GOTIFY_SERVER_URL="https://URL_DES_GOTIFY_SERVERS" ASPNETCORE_URLS="http://0.0.0.0:8681" ASPNETCORE_ENVIRONMENT=Production /root/.dotnet/dotnet '/opt/iGotify/iGotify Notification Assist.dll' `

export habsch noch vor die variablen gemacht :)

```
igotify:/opt/iGotify# export ASPNETCORE_ENVIRONMENT=Production
igotify:/opt/iGotify# /root/.dotnet/dotnet '/opt/iGotify/iGotify Notification Assist.dll'
File is created.
Client - Token: #############
Gotify - Url: wss://#############/stream?token=#############
SecNtfy Server - Url: https://api.secntfy.app/api
Client connecting...Done!
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://0.0.0.0:8681
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /opt/iGotify
```

soooo jetzt nur noch den openrc-run hinkriegen, dann habsch auch nen kompletten guide für dich für alpine :)
achja und testen obs geht hahahhaha

**Comment by androidseb25** [comment]
Ahh ok gut
Wäre cool fürs Wiki nen alpine Guide :D

**Comment by nicedevil007** [comment]
> Ahh ok gut Wäre cool fürs Wiki nen alpine Guide :D

also Test obs geht mit meinem temporären command zum laufen lassen geht mal
ich hab dein Repo gerade geforked aber das wiki is da ja net dabei, wie konnte man das denn nochmal contributen?

**Comment by androidseb25** [comment]
Du kannst dann testen über den neuen API Entry Point wo Test/devicetoken steht

**Comment by nicedevil007** [comment]
> Du kannst dann testen über den neuen API Entry Point wo Test/devicetoken steht

wie gesagt gehen tuts schon ;) hab proxmox als test mal missbraucht, kam instant aufn handy an

**Comment by androidseb25** [comment]
Schau mal jetzt ob du das Wiki bearbeiten kannst

**Comment by nicedevil007** [comment]
Vielleicht hat hier ja wer ne Ahnung wie das mit openrc-run funktioniert, ich bekomme durchgehend den `service: Exec format error`

```bash
#!/sbin/openrc-run
export IGOTIFY_CLIENT_TOKEN=#############
export GOTIFY_SERVER_URL="https://#############"
export ASPNETCORE_URLS="http://0.0.0.0:8681"
export ASPNETCORE_ENVIRONMENT=Production

name="iGotify Notification Service"
description=""
command="/root/.dotnet/dotnet"
command_args="/opt/iGotify/iGotify Notification Assist.dll"
command_user="root:root"
```

@wiki => jo das geht jetzt :) wills aber erst alles reinhauen, wenns dann noch mit dem openrc-run gefixed is

**Comment by androidseb25** [comment]
Hast du auch die richtige Plattform genommen?

Den Fehler kenn ich nur wenn man die falsche Plattform nutzt, also `arm64` statt `amd64`

**Comment by nicedevil007** [comment]
jo hab ich ;) weil den command so in der shell absenden geht halt einfach schon (test von oben war damit)

**Comment by androidseb25** [comment]
Mmmmh ich schau es mir dann mal an wen. Ich wieder zuhause bin 

Was für eine alpine linux Version nutzt du?

**Comment by nicedevil007** [comment]
igotify:~# cat /etc/os-release
NAME="Alpine Linux"
```bash
ID=alpine
VERSION_ID=3.20.0_alpha20231219
PRETTY_NAME="Alpine Linux edge"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://gitlab.alpinelinux.org/alpine/aports/-/issues"
```

**Comment by androidseb25** [comment]
Und Architektur x86_64?

**Comment by nicedevil007** [comment]
```bash
igotify:~# uname -a
Linux igotify 6.5.11-7-pve #1 SMP PREEMPT_DYNAMIC PMX 6.5.11-7 (2023-12-05T09:44Z) x86_64 Linux
```

**Comment by nicedevil007** [comment]
vergiss einfach alles... layer8... wenn über der ersten zeile ne leerzeile ist... ich baus noch fertig das wir auch stoppen können, rest folgt :)

**Comment by nicedevil007** [comment]
dein wiki kann man direkt editieren ohne das du es wie art pullrequest drüber schaust?

würde es bissl umbauen wenn das ok ist, worst case stellst alten commit her?
also brauchen ja jetzt unterscheidung zwischen systemd install und nen alpine linux bzw. openrc-run

anstatt überschriften würde ich das mit kommentaren in einem script reinknallen

also anstatt so:

1. Download and install dotnet on your system

```bash
curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin -c 8.0
```

2. Add dotnet to `$PATH`
   
```bash
echo 'export DOTNET_ROOT=$HOME/.dotnet' >> ~/.bashrc
echo 'export PATH=$PATH:$HOME/.dotnet' >> ~/.bashrc
source ~/.bashrc
```

würde ich machen so:

```bash
# Download and install dotnet on your system
curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin -c 8.0

# Add dotnet to `$PATH`
echo 'export DOTNET_ROOT=$HOME/.dotnet' >> ~/.bashrc
echo 'export PATH=$PATH:$HOME/.dotnet' >> ~/.bashrc
source ~/.bashrc
```

vorteil man kann am ende den ganzen block kopieren :)

**Comment by androidseb25** [comment]
Nein lass das mal so erstmal ich muss auch erstmal mit Wiki's schreiben auseinandersetzen 

Erstell einfach ne neue Seite

**Comment by nicedevil007** [comment]
> Nein lass das mal so erstmal ich muss auch erstmal mit Wiki's schreiben auseinandersetzen
> 
> Erstell einfach ne neue Seite

alles klar, ich bau dir ne neue und du kannst dann übernehmen was du brauchst :)

**Comment by nicedevil007** [comment]
schaus dir mal an, denke habe fertig und läuft ja hier jetzt auch können wir also das feature request closen

**Comment by androidseb25** [comment]
ok sieht gut aus werde das mir die tage nochmal in ruhe durchlesen
und werde jetzt wieder den haken bei wiki read only reinpacken für das projekt, falls was ist dann schick es mir einfach hierrein oder per mail :)

**Comment by androidseb25** [comment]
Hallo Leute mir ist ein Fehler unterlaufen im Wiki, eure Binaries sind veraltet und von der Falschen Seite (Testrepo) gekommen.

Bitte ladet euch die neuen Binaries unter der neuen url herunter, diese findet ihr im aktualisiertem Wiki.

Sorry nochmal zu dem missgeschickt
