### ISSUE TITLE
newline oder zeilenumbruch

### ISSUE THREAD

**Issue by dasfranky1** [androidseb25/iGotify-Notification-Assistent#16]
Ich habe das Problem, dass der Zeilenumbruch auf dem iPhone nicht korrekt dargestellt wird. 
In der gotify push sind die Umbrüche richtig, in der igotify app nicht (alle).

ich sende von Linux einen Multiline echo in eine Datei, die Datei wird per gotify push  (gotify push -t "titel" -p X < datei) gesendet.

**Comment by androidseb25** [comment]
Kann das vllt am Markdown hängen das die Umbrüche nicht korrekt sind?

**Comment by androidseb25** [comment]
Wenn du ein beispiel hättest könnte ich das noch besser nachvollziehen

**Comment by dasfranky1** [comment]
Beispiel: 
ein script wird per cron alle X minuten ausgeführt. im script wird der dateiinhalt wie folgt gefüllt und gesendet:
# Build content
echo "
Hostname: $hostname
Uptime: $uptime_hours [hours]
Location: $currentlocation
Boottime: $boottime
Systemtime: $currenttime
Network: eth0 $networketh0
Network: eth1 $networketh1
Network: tun0 $networktun0
CPU Load: $load1 $load5 $load15 [1/5/15]
RAM Usage: $ramused of $ramtotal [GB]
Temp CPU: $cputemp
Temp NVME1: $tempnvme11-$tempnvme12
Temp NVME2: $tempnvme21-$tempnvme22
Temp SSD: $tempsda $tempsdb
DiskUsage Sys: $disk_sys
DiskUsage DB: $disk_sql
DiskUsage Data: $disk_data
DiskUsage Backup: $disk_ba
DiskUsage RAMdisk: $disk_ram
Apps Analyseapp: $process_analyse
Apps Captureapp: $process_capture
Apps Storage: $process_storage
Apps Dump: $process_dump
FilesQ PreProcess: $traceqprepro
FilesQ PreAnalysis: $traceqpreana
Interfaces WLAN: $countwlanint
Interfaces MON: $countwlanmon
IM: ${arr_mon[*]}
CH: ${arr_chan[*]}
HT: ${arr_ht[*]}
" | tee -a $tmpfile
gotify push -t "titel" -p 1 < $tmpfile

Auf dem iPhone:
![IMG_1685](https://github.com/androidseb25/iGotify-Notification-Assistent/assets/120713642/143a4d97-d120-46f3-916c-6541983b0376)

im Web:
![ex_web](https://github.com/androidseb25/iGotify-Notification-Assistent/assets/120713642/9081a692-da67-443d-8e1a-49e2f1c31405)

**Comment by androidseb25** [comment]
Es sieht so aus als würde er beim Interpretieren des Textes als Markdown den normalen Zeilenumbruch nicht darstellen nehmen, probiere mal `</br> ` das sollte funktionieren, aber ich schau mal bis zum nächsten Release ob ich das auch so hinbekomme

**Comment by dasfranky1** [comment]
mit den </br> wird der Inhalt korrekt angezeigt, aber im web client sowie in der preview der push-nachricht sind die </br> im Klartext zu lesen.

**Comment by androidseb25** [comment]
ok gut wie gesagt ich schau es mir an und versuche es mit dem nächsten release zu fixen

**Comment by androidseb25** [comment]
So mal schnell im Internet gestöbert und konnte das Problem lösen, ist im nächsten Update definitiv dabei (siehe Bilder)


![Vorher](https://github.com/androidseb25/iGotify-Notification-Assistent/assets/11179091/84054c56-bffb-463a-87e8-053cf5f143a5)

![Nachher](https://github.com/androidseb25/iGotify-Notification-Assistent/assets/11179091/691347d0-df5c-4e6b-bf68-6963447fac2d)
