### ISSUE TITLE
Hinweis für andere User: iGotify und Gotify hinter Nginx Proxy Manager, Advanced Settings nötig

### ISSUE THREAD

**Issue by TBT-TBT** [androidseb25/iGotify-Notification-Assistent#18]
Kein Bug, sondern ein Kofigurationshinweis für Nutzer von Nginx Proxy Manager. Bezieht sich auf das Video "iGotify - PUSH NOTIFICATIONS jetzt auch auf dem IPHONE" von [Raspberry Pi Cloud](https://www.youtube.com/@RaspberryPiCloud) https://youtu.be/hKlHL4wGgpY?t=650 

Bei der Verwendung von 2x Nginx Proxy Manager Einträgen für Gotify und die iGotify API benötigen einer oder beide (sicherheitshalber für beide Proxy Einträge konfigurieren) Proxies auf dem Advanced Tab folgende Einträge, damit Push Notifications auch wirklich funktionieren:

```
proxy_set_header   Host $http_host;
proxy_connect_timeout   1m;
proxy_send_timeout      1m;
proxy_read_timeout      1m;
```

Diese Einträge stammen von https://gotify.net/docs/nginx .

**Comment by androidseb25** [comment]
Hi, ich nutze auch den npm aber mit den push notifications hab ich bis jetzt keine Probleme gehabt. 
Wenn du die compose Datei nutzt so wie ich die zur Verfügung gestellt habe, hört der Container innerhalb des stacks auf den gotify Server und muss nicht extra raus telefonieren.

**Comment by androidseb25** [comment]
Hinweis in die Readme mit aufgenommen danke
