### ISSUE TITLE
Probleme Push Benachrichtigung

### ISSUE THREAD

**Issue by Sebeck81** [androidseb25/iGotify-Notification-Assistent#19]
Hallo,

als erstes, vielen Dank für die Arbeit und Mühe für die Erstellung der App. 

Ich bekomme leider keine Pushnachrichten, nur wenn ich in der App bin und manuell synchronisiere erscheinen die Nachrichten. 

Hat da jemand eine Idee?

Vielen lieben Dank

**Comment by androidseb25** [comment]
Hast du dir schonmal die geschlossenen Issues angeschaut?

Vielleicht findest du dort schon einen Lösungsansatz.

Weil ohne Informationen von Logs/docker compose config oder ähnlichen kann ich dir nicht helfen.

**Comment by androidseb25** [comment]
Geschlossen wegen Inaktivität
