### ISSUE TITLE
[Feature Request] Dringende Mitteilungen auf iOS Devices

### ISSUE THREAD

**Issue by SoundFreak97** [androidseb25/iGotify-Notification-Assistent#2]
Hallo,

Wäre es möglich die App so anzupassen, dass man über einer Priority von z.Bsp. 8 die Nachrichten auch erhält, wenn das iPhone auf Nicht Stören steht?

Es gibt mittlerweile Apps welche solch eine Funktion integriert haben, dort taucht dann unter den Einstellungen -> Mitteilungen -> App
Kritische Hinweise und Dringende Mitteilungen auf.

Gruß

**Comment by androidseb25** [comment]
Danke, ich werde mal schauen was sich machen lässt

**Comment by androidseb25** [comment]
Könntest du mir eine Beispiel App nennen? Da ich nicht weiß ob Apple das für diese App erlaubt.

Da laut Apple docs Definition ein spezielle Berechtigung direkt von Apple benötigt wird.


> ... Critical alerts require a special entitlement issued by Apple.

Quelle: https://developer.apple.com/documentation/usernotifications/unauthorizationoptions/unauthorizationoptioncriticalalert

**Comment by Nollknolle** [comment]
NINA macht das. Da steht dann "Dringlich" in der Nachricht.

**Comment by SoundFreak97** [comment]
Stimmt.

NINA, KatWarn und die neuste Version der Loxone App fallen mir gerade spontan ein.

Es gibt anscheinend die Möglichkeit den benötigten Key bei Apple anzufordern: https://developer.apple.com/contact/request/notifications-critical-alerts-entitlement/

Jenachdem wie streng Apple ist, sollte es für eine Notifications App hoffentlich möglich sein :)

**Comment by androidseb25** [comment]
> Stimmt.
> 
> NINA, KatWarn und die neuste Version der Loxone App fallen mir gerade spontan ein.
> 
> Es gibt anscheinend die Möglichkeit den benötigten Key bei Apple anzufordern: https://developer.apple.com/contact/request/notifications-critical-alerts-entitlement/
> 
> Jenachdem wie streng Apple ist, sollte es für eine Notifications App hoffentlich möglich sein :)

ja ich bin schon dran einen Request zu schreiben mal schauen ob sie es absegnen, ein Knackpunkt könnte sein das auch stink normale Nachrichten drüber gehen ohne jegliche kritische Relevanz.

**Comment by androidseb25** [comment]
Anfrage ist rausgeschickt mal schauen was zurück kommt

**Comment by androidseb25** [comment]
Anfrage wurde genehmigt.

Krtitische Benachrichtigungen sind bei Priorität 10 automatisch aktiv!

**Comment by androidseb25** [comment]
Feature ist dann in iGotify Notification Assist Version 1.0.0.8 und App Version 1.0.4 enthalten
