### ISSUE TITLE
No notifications on iPhone

### ISSUE THREAD

**Issue by nallej** [androidseb25/iGotify-Notification-Assistent#20]
Nice app, thanks. We need it for iPhone.

+ No problem loggin in all go as it should
+ All users and Clients show as is
- I do have a problem, getting a notification I get the alarm signal but can't see any message.
- Also no old messages at all in the iPhone.

---
gotify has been recreated
igotify exited with code 0
igotify has been recreated
igotify exited with code 0
igotify has been recreated
gotify   | Starting Gotify version 2.4.0@2023-09-17-08:24:00
gotify   | Started Listening for plain HTTP connection on :80
igotify  | File is created.
igotify  | Client - Token: <Token>
igotify  | Gotify - Url: ws://gotify/stream?token=<Token>
igotify  | Client connecting...Done!
gotify   | 2024-01-10T14:41:36+02:00 | 200 |     4.07984ms |     172.18.0.10 | GET      "/stream?token=[masked]"
igotify  | Reconnection happened, type: Initial
igotify  | info: Microsoft.Hosting.Lifetime[14]
igotify  |       Now listening on: http://[::]:8080
igotify  | info: Microsoft.Hosting.Lifetime[0]
igotify  |       Application started. Press Ctrl+C to shut down.
igotify  | info: Microsoft.Hosting.Lifetime[0]
igotify  |       Hosting environment: Production
igotify  | info: Microsoft.Hosting.Lifetime[0]
igotify  |       Content root path: /app
gotify   | 2024-01-10T14:41:37+02:00 | 200 |    2.217134ms |   <Wan IP> | GET      "/application"
gotify   | 2024-01-10T14:41:37+02:00 | 200 |    8.632602ms |   <Wan IP> | GET      "/message?since=0"
gotify   | 2024-01-10T14:41:43+02:00 | 200 |    1.738538ms |   <Wan IP> | GET      "/application"
gotify   | 2024-01-10T14:41:43+02:00 | 200 |    4.985731ms |   <Wan IP> | GET      "/current/user"
gotify   | 2024-01-10T14:41:43+02:00 | 200 |    1.349784ms |   <Wan IP> | GET      "/message?since=0"
gotify   | 2024-01-10T14:41:46+02:00 | 200 |    3.541318ms |   <Wan IP> | GET      "/current/user"
gotify   | 2024-01-10T14:41:46+02:00 | 200 |    1.386348ms |   <Wan IP> | GET      "/application"
gotify   | 2024-01-10T14:41:47+02:00 | 200 |    2.404043ms |   <Wan IP> | GET      "/stream?token=[masked]"
gotify   | 2024-01-10T14:41:50+02:00 | 200 |   81.480124ms |   <Wan IP> | POST     "/message"
igotify  | Message converted: {"id":4,"appid":1,"message":"```\nThis is a test of the notification target 'Gotify'\n```","title":"Test notification","priority":1,"extras":{"clientdisplay":{"contentType":"text/markdown"}},"date":"2024-01-10T14:41:50.341571427+02:00"}
igotify  | 
gotify   | 2024-01-10T14:41:57+02:00 | 200 |    1.233067ms |   <Wan IP> | GET      "/application"
gotify   | 2024-01-10T14:41:57+02:00 | 200 |    3.263905ms |   <Wan IP> | GET      "/message?since=0"
gotify   | 2024-01-10T14:42:04+02:00 | 200 |    1.706637ms |   <Wan IP> | GET      "/message?since=0"
gotify   | 2024-01-10T14:42:07+02:00 | 200 |    6.773183ms |   <Wan IP> | GET      "/application"
gotify   | 2024-01-10T14:42:07+02:00 | 200 |    1.133712ms |   <Wan IP> | GET      "/message?since=0"
gotify   | 2024-01-10T14:44:09+02:00 | 200 |    6.571001ms |   <Wan IP> | GET      "/application"
gotify   | 2024-01-10T14:44:09+02:00 | 200 |    1.467014ms |   <Wan IP> | GET      "/message?since=0"
gotify   | 2024-01-10T14:44:15+02:00 | 200 |    9.005309ms |   <Wan IP> | GET      "/current/user"
gotify   | 2024-01-10T14:44:16+02:00 | 200 |    1.177752ms |   <Wan IP> | GET      "/application"
gotify   | 2024-01-10T14:44:16+02:00 | 200 |    1.200915ms |   <Wan IP> | GET      "/message?since=0"
gotify   | 2024-01-10T14:44:25+02:00 | 200 |    3.418988ms |   <Wan IP> | GET      "/client"
gotify   | 2024-01-10T14:44:28+02:00 | 200 |    1.420087ms |   <Wan IP> | GET      "/user"
gotify   | 2024-01-10T14:44:33+02:00 | 200 |    3.435814ms |   <Wan IP> | GET      "/client"
gotify   | 2024-01-10T14:44:34+02:00 | 200 |    1.438739ms |   <Wan IP> | GET      "/user"
gotify   | 2024-01-10T14:44:40+02:00 | 200 |     103.791µs |   <Wan IP> | GET      "/version"
igotify  | warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
igotify  |       Failed to determine the https port for redirect.
gotify   | 2024-01-10T14:44:43+02:00 | 200 |     7.79832ms |   <Wan IP> | GET      "/application"
gotify   | 2024-01-10T14:44:43+02:00 | 200 |    1.289257ms |   <Wan IP> | GET      "/message?since=0"
gotify   | 2024-01-10T14:44:52+02:00 | 200 |   20.346748ms |   <Wan IP> | POST     "/message"
igotify  | Message converted: {"id":5,"appid":1,"message":"```\nThis is a test of the notification target 'Gotify'\n```","title":"Test notification","priority":1,"extras":{"clientdisplay":{"contentType":"text/markdown"}},"date":"2024-01-10T14:44:52.437477394+02:00"}
igotify  | 
gotify   | 2024-01-10T14:44:54+02:00 | 200 |    1.068236ms |   <Wan IP> | GET      "/application"
gotify   | 2024-01-10T14:44:54+02:00 | 200 |    3.256869ms |   <Wan IP> | GET      "/message?since=0"
gotify   | 2024-01-10T14:45:06+02:00 | 200 |   16.641235ms |   <Wan IP> | POST     "/message"
igotify  | Message converted: {"id":6,"appid":2,"message":"```\nThis is a test of the notification target 'gotify-notifications'\n```","title":"Test notification","priority":1,"extras":{"clientdisplay":{"contentType":"text/markdown"}},"date":"2024-01-10T14:45:06.308357671+02:00"}
igotify  | 
gotify   | 2024-01-10T14:45:08+02:00 | 200 |    1.090436ms |   <Wan IP> | GET      "/application"
gotify   | 2024-01-10T14:45:08+02:00 | 200 |    5.502843ms |   <Wan IP> | GET      "/message?since=0"
gotify   | 2024-01-10T14:45:10+02:00 | 200 |    1.005231ms |   <Wan IP> | GET      "/application"
gotify   | 2024-01-10T14:45:10+02:00 | 200 |   16.426426ms |   <Wan IP> | GET      "/message?since=0"

**Comment by nallej** [comment]
Yes I have a token.
What I see is the popup and heare the alarm

**Comment by androidseb25** [comment]
Sorry but I don't know where you're problem is when you getting the push notifications.

**Comment by pandora1986** [comment]
please provide us screenshots from your gotify webside, where you can see the previous alerts
also provide us a screenshot of your app on the iphone

do you have this problem in your LAN or/and outside of it?
is your igotify external reachable?
do you have setup different users?

**Comment by nallej** [comment]
It's fixed. I had 2 users and switching back to the first fixed the issue.
