### ISSUE TITLE
[BUG] Seit dem letzten Update, werden die Push-Nachrichten "verschlüsselt" angezeigt

### ISSUE THREAD

**Issue by VolleyTom8** [androidseb25/iGotify-Notification-Assistent#27]
Seit dem letzten Update, werden die Push-Nachrichten am IPhone komisch angezeigt.
![IGotifyNotificationDisplayNOK](https://github.com/androidseb25/iGotify-Notification-Assistent/assets/66139299/a6ee534b-7976-4c8b-ac84-cecbe5852495)
Wenn man die App öffnet, wird die Nachricht richtig angezeigt!

Infos:
AppVersion: 1.1 (15)
Server Version: 2.4.0
Api Server Version: 1.1.0.0

Danke für den fix.
Tom

**Comment by androidseb25** [comment]
Kannst du die App nochmal neu einrichten? 

Sieht nämlich so aus als ob er den private key nicht richtig angelegt hat 🤔

**Comment by VolleyTom8** [comment]
Ich habe mich abgemeldet und neu angemeldet, danach wieder das Problem!
Was genau meinst mit "neu einrichten"?

**Comment by androidseb25** [comment]
> Ich habe mich abgemeldet und neu angemeldet, danach wieder das Problem! Was genau meinst mit "neu einrichten"?

einmal deinstallieren das meine ich mit neu einrichten

**Comment by VolleyTom8** [comment]
Habe deinstalliert, die Devices aus der Liste gelöscht im UI und dann neu installiert, aber immer noch werden neue Nachrichten beim PUSH nicht korrekte angezeigt, aber in der App ist alles ordnungsgemäß.

**Comment by androidseb25** [comment]
was für ein iphone mit ios hast du? dann sende ich mal nen test in clear text

In der App wird alles clear text angezeigt da diese direkt vom gotify kommt

**Comment by VolleyTom8** [comment]
IPhone14 mit IOS 17.2.1

**Comment by VolleyTom8** [comment]
test
test

ist angekommen

**Comment by androidseb25** [comment]
ok und jetzt?

**Comment by VolleyTom8** [comment]
Nur der Test war lesbar, die anderen Nachrichten nicht.

**Comment by androidseb25** [comment]
kamen jetzt 2 nachrichten und mit welchen content?

**Comment by VolleyTom8** [comment]
Nicht lesbar (so wie die Push-Nachrichten die ich auch bekomme). Leider keinen Screenshot gemacht und durch anklicken sind sie weg.
Und auch in der App nicht ersichtlich.

**Comment by VolleyTom8** [comment]
![image0](https://github.com/androidseb25/iGotify-Notification-Assistent/assets/66139299/e3eb1cac-4129-4a0d-ae4d-377e81991d3a)

**Comment by androidseb25** [comment]
Sehr komisch 🧐

Es können eigentlich nur 3 Sachen sein die Fehlschlagen:

- Public Key passt nicht zum Private Key (was eher unwahrscheinlich ist)
- Es wird keine Message Id gesendet oder ist nicht lesbar
- Der Status erhalten produziert nen Fehler

Ich untersuche mal den Sachverhalt weiter, isr definitiv nen App Problem.

Ich entschuldige mich erstmal für den fehler

**Comment by VolleyTom8** [comment]
Kein Problem, falls du noch was brauchst, sag es mir einfach.

**Comment by VolleyTom8** [comment]
Durch das IOS-Update auf 17.3 wurde das Problem mit den nicht lesbaren Push-Nachrichten gelöst, man kann die Nachrichten wieder lesen.

**Comment by androidseb25** [comment]
Wie was echt jetzt?!?

Also hing das Problem mit iOS 17.2.1 zusammen. Interessant 🤔

Dann schließe ich den issue mal....
