### ISSUE TITLE
[FEATURE REQUEST] sending push to other user

### ISSUE THREAD

**Issue by gladiatormax** [androidseb25/iGotify-Notification-Assistent#31]
**Describe the bug**
I have 2 users in gotify and both have some apps on it.
I have a myspeed app and the second user not, but we both recieves the push messages from igotify, they are not in his gotify list so only push, they are in my list.

**Expected behavior**
Only send push to the user where the api is configured.

**Smartphone (please complete the following information):**
 - Device: both on iphone

Here is my compose file,

version: "3.8"

services:
  gotify:
    image: gotify/server # Uncommand correct server image
    # image: gotify/server-arm7
    # image: gotify/server-arm64
    ports:
      - 8680:80
    environment:
      - GOTIFY_DEFAULTUSER_PASS=xxxxxxxxxxxxxx # Change me!!!!!
      - TZ=Europe/Brussels
    restart: unless-stopped
    volumes:
      - /docker-local/gotify:/app/data

  igotify-notification: # (iGotify-Notification-Assistent)
    image: ghcr.io/androidseb25/igotify-notification-assist:latest
    pull_policy: always
    ports:
      - 8681:8080
    environment:
      - IGOTIFY_CLIENT_TOKEN="xxxxxxxxxxxxxxx"  # create a client in gotify an add here the client token
      - GOTIFY_SERVER_URL="http://gotify"  # default container name from gotify server
    restart: always
    volumes:
      - igotify-notification-data:/app/data

volumes:
  gotify-data:
  igotify-notification-data:

Al other apps are working fine.

**Comment by androidseb25** [comment]
Hi, 

Multiuser support is not supported! Only notifications will be sent from the configured client in the compose file when it receives one. Please check your igotify-token.txt, which is in the data path of the igotify-notification container, to see whether your device is stored there twice, which receives the notification

**Comment by gladiatormax** [comment]
> Hi,
> 
> Multiuser support is not supported! Only notifications will be sent from the configured client in the compose file when it receives one. Please check your igotify-token.txt, which is in the data path of the igotify-notification container, to see whether your device is stored there twice, which receives the notification

Hi thx for the quick answer.
I did a check in the file, but only 3 different devices in there, which is normal my ipad and iphone and the second user device.
So we will be waiting on multiuser support :-)

**Comment by androidseb25** [comment]
yeah that's a quite bit tricky because, gotify doesn't support multiusers because of the dev can't do that :/ 
see also the Feature Request i done by gotify: https://github.com/gotify/server/issues/623

the only way is to create X igotify Container and managed these in the app, what is an bad solution for this purpose

**Comment by jmattheis** [comment]
> the only way is to create X igotify Container and managed these in the app, what is an bad solution for this purpose

Would it not be possible to configure multiple client tokens on the assistant container and then establish multiple websocket connections to get messages from multiple users?

**Comment by androidseb25** [comment]
i currently search a way to establish multiple websockets and set the correct token to an user, without an database in the background.

**Comment by androidseb25** [comment]
Changed it from Bug to Feature Request

**Comment by androidseb25** [comment]
Here are you find informations for the Multiuser support feature #34 the PR is #35

**Comment by androidseb25** [comment]
Short Update for everyone here....

iOS App is to 95% ready, only need long running tests and formatting code
checking performance and so on

Release is near :)

**Comment by androidseb25** [comment]
Apple also approved the Final Build

Release is Wednesday at 18 o'clock CET

i close the issue now
