### ISSUE TITLE
Einrichtungs hilfe

### ISSUE THREAD

**Issue by Hendrik292** [androidseb25/iGotify-Notification-Assistent#33]
Ich habe den gotify server Auf Windows Installiert. Jetzt weiß ich nicht, wie ich die IOS App einrichten soll, was ich bei der API URL hinschreiben soll und ob ich beim Server noch was ändern muss.

Ich bin für jede Hilfe dankbar.

**Comment by androidseb25** [comment]
Na dein Windows hat doch ne lokale IP oder nicht?

Und über die erreicht du den Container mit dem Port.

Beispiel:

`192.168.178.50:8680` ist dein Gotify Server

`192.168.178.50:8681` ist der Assistent

**Comment by androidseb25** [comment]
Es kann durchaus sein das du die Ports noch in der Windows FW freigeben musst.

**Comment by Hendrik292** [comment]
Ich habe jetzt als Port für die Android App 1337 Genutzt Ich habe den Assistent noch nicht eingerichtet, ich weiß nämlich nicht, wie ich ihn einrichten soll.

**Comment by androidseb25** [comment]
Android App ist es nicht sondern iOS.


Einrichtung steht doch in der Readme

**Comment by androidseb25** [comment]
Nutzt du Docker auf deinem Windows?

**Comment by Hendrik292** [comment]
Nein. Ich benutze das hier. 
https://github.com/gotify/server/releases/download/v2.4.0/gotify-windows-amd64.exe.zip
Kenne mich leider nicht, wenn dem Thema aus.

**Comment by androidseb25** [comment]
Ich würde mich später melden und dir dann ne Anleitung geben, muss das erstmal selbst testen...

**Comment by Hendrik292** [comment]
Okay, danke.

**Comment by androidseb25** [comment]
Hi ich muss dir leider mitteilen das es nicht möglich ist meinen Assistenten unter Windows zum laufen zu bekommen, hab jetzt 3 Stunden damit verbracht windows meine environment variablen zu vergeben und diese überall einzutragen wo es geht, aber es startet einfach nicht. am besten du installierst dir docker desktop und lässt beides darüber laufen
