### ISSUE TITLE
[BUG] API cannot be accessed behind reverse proxy path

### ISSUE THREAD

**Issue by marchein** [androidseb25/iGotify-Notification-Assistent#36]
**Describe the bug**
Currently I have both the gotify and igotify container published using a nginx reverse proxy. 
The gotify container is published with the domain gotify.domain.tld and the api container using gotify-api.domain.tld. 
Now I tried using the location and proxy_pass parameter of nginx and publish the api at gotify.domain.tld/api/. 
If I open this url in the browser I get the same igotify api page. 

I tried to setup the igotify app which cannot access the api as it seems...

**Expected behavior**
The app would connect exactly like it would with the gotify-api.domain.tld entry. 

**Screenshots**
![image](https://github.com/androidseb25/iGotify-Notification-Assistent/assets/4535391/7a2c4b27-ea18-4de9-83de-570b29864e61)

**Smartphone (please complete the following information):**
 - Device: iPad Pro 11" M1
 - OS: iPadOS 17.3.1
 - Version of Container 1.1.0.0
 - Version of iGotify 1.1.1

**Additional context**

**Comment by androidseb25** [comment]
I think the problem would be the routing of the api,

did you try with postman if you can access the api endpoinds?

**Comment by marchein** [comment]
I tried just the /version route which delivers the exact same result:
https://gotify-api.domain.tld/version vs. https://gotify.domain.tld/api/version:
```
{
    "version": "1.1.0.0",
    "commit": "5a352c275cdc4920b865a96c945aecc7",
    "buildDate": "2024-02-01T11:03:40"
}
```

**Comment by androidseb25** [comment]
Did you try the other endpoints?
Every endpoint of the other must be response with an error when you try it with dummy data

**Comment by marchein** [comment]
All results of the different endpoints are the same across both hosts. 

```
{
    "Message": "Fehler beim hinzugefügen des Gerätes!",
    "Successful": false
}
```


```
{
    "Message": "Fehler beim löschen des Gerätes!",
    "Successful": false
}
```

**Comment by androidseb25** [comment]
how do you write the api?

did you write the url like this: `gotify.domain.tld/api`?
when yes try to add it without `/api` because the app call at this point `gotify.domain.tld/api/api/version`

**Comment by marchein** [comment]
I tried without the /api now and that let me login. 

Now I receive this error.. tried reinstalling, restarting the iGotify container and deleting the iOS clients in gotify ...

![image](https://github.com/androidseb25/iGotify-Notification-Assistent/assets/4535391/5cf2743b-508e-42d8-9799-941ffe6d145d)

```

09:53:58.658 INFO Logger.getInstance():30 - ♻️ - Initialize iGotify Logger
  
09:53:58.665 INFO SecNtfy.initialize():65 - ♻️ - API URL https://api.secntfy.app
  
09:53:58.667 INFO SecNtfy.initialize():66 - ♻️ - Bundle Group group.sr.iGotify
  
09:53:58.887 INFO SecNtfy.initialize():77 - PubKey: MIIBCgKCAQEAwUxKzLs5Cu/63vULgxJGb4vHG+aXyll3vq5Z9hbBgQ5KjhBwPWCYay+ozrAqYXsxPl2k5MfJRidjfG4/bUTZgVLA+AjGmm0zaFhengyG5SwiWkEL9Js1oP7ZYkOcZrlp9Vp8pZYZ94QhNeioZNt/fA1MB/kZ5LpvVtDRMQr4KFfcfF+vJjaPe970pE/h0lDRfmnNIkKESVtg5E6O6XB/U6k3PGG18kQ8zuCG7BkJw2LmwFAk7jfxMbgVh3ayHajbaIfAdaq/rCrEmEf3odCXWl/iZRx8KEjDwC9MP76P2IplC17etWremwyg/VZjkZCbG/F+T4C85C6K2EVnMbIhFwIDAQAB
  
09:53:58.890 INFO SecNtfy.initialize():78 - PrivKey: MIIEo*****D5elQ
  
09:53:58.894 INFO SecNtfy.configure():102 - Model: iPhone 15
  
09:53:58.896 INFO SecNtfy.configure():103 - OS: 17.3.1
  
09:53:58.898 INFO SecNtfy.configure():105 - PubKey: MIIBCgKCAQEAwUxKzLs5Cu/63vULgxJGb4vHG+aXyll3vq5Z9hbBgQ5KjhBwPWCYay+ozrAqYXsxPl2k5MfJRidjfG4/bUTZgVLA+AjGmm0zaFhengyG5SwiWkEL9Js1oP7ZYkOcZrlp9Vp8pZYZ94QhNeioZNt/fA1MB/kZ5LpvVtDRMQr4KFfcfF+vJjaPe970pE/h0lDRfmnNIkKESVtg5E6O6XB/U6k3PGG18kQ8zuCG7BkJw2LmwFAk7jfxMbgVh3ayHajbaIfAdaq/rCrEmEf3odCXWl/iZRx8KEjDwC9MP76P2IplC17etWremwyg/VZjkZCbG/F+T4C85C6K2EVnMbIhFwIDAQAB
  
09:53:58.901 INFO SecNtfy.configure():106 - PrivKey: MIIEo*****D5elQ
  
09:53:59.050 VERBOSE AppDelegate.application():83 - APNs token retrieved: 32 bytes
  
09:53:59.053 VERBOSE AppDelegate.application():86 - The token: 6D398*****DD77F
  
09:53:59.055 INFO SecNtfy.setApnsToken():132 - 6D398*****DD77F
  
09:54:46.480 INFO SecNtfy.getInstance():43 - ♻️ - instance init
  
09:54:46.608 ERROR SecNtfy.PostDevice():162 - 🔥 - Failed task Es wurde kein Server mit dem angegebenen Hostnamen gefunden.
  
09:54:46.615 ERROR ContentView.sendFCMToken():27 - getNtfyToken: Optional("Es wurde kein Server mit dem angegebenen Hostnamen gefunden.")
  
09:54:46.621 ERROR ContentView.sendFCMToken():27 - getNtfyToken: Optional("Es wurde kein Server mit dem angegebenen Hostnamen gefunden.")
  

```

**Comment by androidseb25** [comment]
Ok good, did you're find blocker block a domain with api.secntfy.app?

**Comment by marchein** [comment]
I just checked in my AdGuard, but no, it is not blocked 
![image](https://github.com/androidseb25/iGotify-Notification-Assistent/assets/4535391/163e9520-8e58-4c65-9a74-74ed65c834fa)

**Comment by androidseb25** [comment]
Strange this is normally the issue 🤔
I have currently no ideas why you can't connect 

the site secntfy.app can you open?

**Comment by MaxGrmm** [comment]
> I tried without the /api now and that let me login.
> 
> Now I receive this error.. tried reinstalling, restarting the iGotify container and deleting the iOS clients in gotify ...
> 
> ![image](https://private-user-images.githubusercontent.com/4535391/303825954-5cf2743b-508e-42d8-9799-941ffe6d145d.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5OTU2NTAsIm5iZiI6MTcwNzk5NTM1MCwicGF0aCI6Ii80NTM1MzkxLzMwMzgyNTk1NC01Y2YyNzQzYi01MDhlLTQyZDgtOTc5OS05NDFmZmU2ZDE0NWQuanBlZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE1VDExMDkxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwM2MwMWU4OTBjMzNkOGM4ODg4NDAyOTY5MmM3OTk5YmE3NWI0ZmJlYmJjNTAzMTE5ZmUwYjIzZWRjNjk1NmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U1ncwlGTd03rPB7rP2tnDVKAtIasi6MFHjf5sPN0Dg8)
> 
> ```
> 
> 09:53:58.658 INFO Logger.getInstance():30 - ♻️ - Initialize iGotify Logger
>   
> 09:53:58.665 INFO SecNtfy.initialize():65 - ♻️ - API URL https://api.secntfy.app
>   
> 09:53:58.667 INFO SecNtfy.initialize():66 - ♻️ - Bundle Group group.sr.iGotify
>   
> 09:53:58.887 INFO SecNtfy.initialize():77 - PubKey: MIIBCgKCAQEAwUxKzLs5Cu/63vULgxJGb4vHG+aXyll3vq5Z9hbBgQ5KjhBwPWCYay+ozrAqYXsxPl2k5MfJRidjfG4/bUTZgVLA+AjGmm0zaFhengyG5SwiWkEL9Js1oP7ZYkOcZrlp9Vp8pZYZ94QhNeioZNt/fA1MB/kZ5LpvVtDRMQr4KFfcfF+vJjaPe970pE/h0lDRfmnNIkKESVtg5E6O6XB/U6k3PGG18kQ8zuCG7BkJw2LmwFAk7jfxMbgVh3ayHajbaIfAdaq/rCrEmEf3odCXWl/iZRx8KEjDwC9MP76P2IplC17etWremwyg/VZjkZCbG/F+T4C85C6K2EVnMbIhFwIDAQAB
>   
> 09:53:58.890 INFO SecNtfy.initialize():78 - PrivKey: MIIEo*****D5elQ
>   
> 09:53:58.894 INFO SecNtfy.configure():102 - Model: iPhone 15
>   
> 09:53:58.896 INFO SecNtfy.configure():103 - OS: 17.3.1
>   
> 09:53:58.898 INFO SecNtfy.configure():105 - PubKey: MIIBCgKCAQEAwUxKzLs5Cu/63vULgxJGb4vHG+aXyll3vq5Z9hbBgQ5KjhBwPWCYay+ozrAqYXsxPl2k5MfJRidjfG4/bUTZgVLA+AjGmm0zaFhengyG5SwiWkEL9Js1oP7ZYkOcZrlp9Vp8pZYZ94QhNeioZNt/fA1MB/kZ5LpvVtDRMQr4KFfcfF+vJjaPe970pE/h0lDRfmnNIkKESVtg5E6O6XB/U6k3PGG18kQ8zuCG7BkJw2LmwFAk7jfxMbgVh3ayHajbaIfAdaq/rCrEmEf3odCXWl/iZRx8KEjDwC9MP76P2IplC17etWremwyg/VZjkZCbG/F+T4C85C6K2EVnMbIhFwIDAQAB
>   
> 09:53:58.901 INFO SecNtfy.configure():106 - PrivKey: MIIEo*****D5elQ
>   
> 09:53:59.050 VERBOSE AppDelegate.application():83 - APNs token retrieved: 32 bytes
>   
> 09:53:59.053 VERBOSE AppDelegate.application():86 - The token: 6D398*****DD77F
>   
> 09:53:59.055 INFO SecNtfy.setApnsToken():132 - 6D398*****DD77F
>   
> 09:54:46.480 INFO SecNtfy.getInstance():43 - ♻️ - instance init
>   
> 09:54:46.608 ERROR SecNtfy.PostDevice():162 - 🔥 - Failed task Es wurde kein Server mit dem angegebenen Hostnamen gefunden.
>   
> 09:54:46.615 ERROR ContentView.sendFCMToken():27 - getNtfyToken: Optional("Es wurde kein Server mit dem angegebenen Hostnamen gefunden.")
>   
> 09:54:46.621 ERROR ContentView.sendFCMToken():27 - getNtfyToken: Optional("Es wurde kein Server mit dem angegebenen Hostnamen gefunden.")
>   
> ```

Habe das gleiche Verhalten wie der Kollege über mir… 
Sehe die Mitteilungen in der App aber bekomme keine Push Messages mehr. 
im AD GURAD wird ebenfalls nichts geblockt 
Token schon neu erstellt und Container geupdatet

**Comment by androidseb25** [comment]
Siehst du die Webseite secntfy.app?
Weil er kann genau den Punkt zu secntfy nicht auflösen

**Comment by MaxGrmm** [comment]
Ja ich sehe die Webseite und auch das die Anfragen verarbeitet werden. 
![Screenshot 2024-02-15 121947](https://github.com/androidseb25/iGotify-Notification-Assistent/assets/107243839/a9f3ce34-b993-49d2-baf5-5f7802259400)

**Comment by androidseb25** [comment]
Ok, gut gibt es vielleicht noch ne Firewall davor die die Adresse blocken könnte?

**Comment by MaxGrmm** [comment]
Habe mal im ADGUARD ne manuelle Freigabe auf die von dir genannte Domain inkl. Sub-Domains gemacht. 
Scheinbar funktioniert es jetzt.

Benutzerdefinierte Filterregel: 

#Freigabe für iGotify
@@||secntfy.app^


![image](https://github.com/androidseb25/iGotify-Notification-Assistent/assets/107243839/51aa4cc3-4d93-405d-82f2-96b997b41c10)

**Comment by marchein** [comment]
Danke für den Vorschlag!

Ich bevorzuge es in Github Issues auf Englisch zu schreiben, sodass mehr Menschen Zugang zu einer potenziellen Lösung haben. Von daher...

I tried adding the rule to my DNS and I got further. But still no luck....

Now I receive this message within the iGotify Docker Container:

```
Message converted: {"id":4,"appid":2,"message":"```\nThis is a test of the notification target 'Gotify'\n```","title":"Test notification","priority":1,"extras":{"clientdisplay":{"contentType":"text/markdown"}},"date":"2024-02-17T10:20:19.822767958+01:00"}

NO DEVICES FOUND FOR SENDING MESSAGES!
```

Maybe its because the Container expects an API Path of https://domain.tld/<apiEndpoint> instead of https://domain.tld/api/<apiEndpoint>?

**Comment by androidseb25** [comment]
I think it's nothing with the container or gotify because he get a connection. (The notification shows up from gotify in the app) 

The notification you get in the container that no device is found is correct, because he didn't received the device token from the app.

The reason why the app can't connect to https://api.secntfy.app for getting this device token is for me a big mystery. 

There must be something in you're network that block the connection to it 🤔 like a firewall rule or something with the dns or a VPN?


Did you try it with cellular on and WiFi off?

**Comment by marchein** [comment]
I get the same behavior with wifi off and using only my phones cellular data...

**Comment by androidseb25** [comment]
> I get the same behavior with wifi off and using only my phones cellular data...

thats crazy 🤔 i checked at the moment if the IP or domain is blacklist somewhere but everything is good.

I have no ideas why you can't connect...

**Comment by marchein** [comment]
Even tried multiple times to reinstall the app, disabled the private relay feature of iOS, rebooted the phone, tried my iPad instead of the iphone..

**Comment by androidseb25** [comment]
please take a look at the release on wednesday maybe it fix you're error

**Comment by marchein** [comment]
Hi, thank you for the new version.

Its working now, thanks!
