### ISSUE TITLE
[BUG] Notification body is empty (proxmox backup status)

### ISSUE THREAD

**Issue by flexmatics** [androidseb25/iGotify-Notification-Assistent#38]
**Describe the bug**
I'm using Proxmox notification service to delivery backup status to Gotify. Message is received in Gotify instance with both title / body text being fine. However, in iGotify, I can only see title present - the body of the message is blank (see video attached)

**Expected behavior**
I expect message body to be visible in iGotify (not just the title).

**Screenshots**
https://github.com/androidseb25/iGotify-Notification-Assistent/assets/79056776/6698b91e-bde0-4ab5-b876-62a0caf77f19

**Smartphone (please complete the following information):**
 - Device: iPhone 14 PRO
 - OS: iOS 17.3.1
 - Version of Container: ghcr.io/androidseb25/igotify-notification-assist:latest
 - Version of iGotify: 1.1.1 (18)

**Additional context**

**Comment by androidseb25** [comment]
I know this bug. Still waiting of an response from the dev.

https://github.com/gonzalezreal/swift-markdown-ui/issues/296

Currently I will cut the message in the new update...

**Comment by androidseb25** [comment]
Here an example in german. Coming in version 1.2

![Bildschirmfoto 2024-02-21 um 21 21 04](https://github.com/androidseb25/iGotify-Notification-Assistent/assets/11179091/c0e39ea9-df99-4d14-a7ef-162e55e45fab)
