### ISSUE TITLE
[BUG] Keine Pushmessages mehr

### ISSUE THREAD

**Issue by nicedevil007** [androidseb25/iGotify-Notification-Assistent#39]
**Describe the bug**
Moin moin, bekomme seit ca 1er Woche erneut keine Pushnachrichten mehr. Angezeigt wird alles beim öffnen der App.

**Smartphone (please complete the following information):**
 - Device: iPhone 15 Pro Max
 - OS: iOS 17.3.1
 - Version of Container (bare metal) 1.1.0
 - Version of iGotify 1.1.0

**Comment by androidseb25** [comment]
Ich brauch mal den Log um zu sehen was der sagt. Sonst kann ich dir nicht helfen.

**Comment by nicedevil007** [comment]
ein Dienst scheint sich aufgehangen zu haben auf LXC im Proxmox. Ggf. war hier ein Update dran schuld. Für alle anderen die das lesen sollten, startet mal gotify und igotify neu auf dem LXC (falls ihr die manual installation gemacht habt).
