### ISSUE TITLE
[BUG] Pushmessages nach Update von Serverpaketen

### ISSUE THREAD

**Issue by nicedevil007** [androidseb25/iGotify-Notification-Assistent#40]
Moin Seb noch einmal,

ich habe heute wieder das Problem gehabt, das keine Pushmessages mehr kamen. Aus dem letzten Issue hatte ich nun ja noch im Kopf, dass meine automatisierten Updates ggf. für das Problem sorgen.

Dieses Mal gleich geschaut was der Dienst von dir so sagt:

![image](https://github.com/androidseb25/iGotify-Notification-Assistent/assets/17103076/259b988f-3fc6-43a5-94a3-18d4edfdee0d)

Kann man da jetzt nicht was bauen, wenn er diese Meldung bekommt, dass er einfach in 1 Min es erneut versuchen soll den iGotify Dienst zu restarten?

EDIT: Also natürlich kann ich das jetzt alles im Script mit einbauen, dass mein Ansible am Ende vom Update nen restart vom Service macht, aber net jeder von unseren Leuten hier wird wohl Ansible haben ;)

**Comment by androidseb25** [comment]
Na kannst du nicht sagen dass er den Service Restarten soll?

Das hat ja jetzt direkt nichts mit mir zu tun...

`systemd` hat ja den Punkt

```
Restart=always
RestartSec=60
```

**Comment by androidseb25** [comment]
Jetzt noch eine Frage was aktualisierst du denn da?

Der Container hat ja bis jetzt kein Update bekommen. Das kommt ja erst morgen 😅

**Comment by nicedevil007** [comment]
Ich hab ja die "linux manual installation", d.h. bei mir läuft der ganze kram auf nem AlmaLinux, dass sowohl gotify wie auch iGotify beherbergt.

Mein Ansible macht da nix anderes wie nach den "OS Updates" zu suchen und zu installieren. Wenn da ggf. mal nen Update dabei war wo einer der Dienste ggf. noch abhängigkeiten hätten, scheints wohl in dieses Issue zu laufen.

Ich kann das easy beheben (habs gerade auch schon gemacht). Einfach bei mir im Ansible Playbook sowas hier geadded:

```json
        - name: Restart iGotify
          ansible.builtin.systemd_service:
            state: restarted
            name: "{{ item }}"
            daemon_reload: True
          with_items:
            - iGotify
          when: "'ansible' in inventory_hostname"
```

diejenigen hier, die aber ggf. net ganz so tief im Linux stecken, kriegen das sicher net mit und machen dann maximal nen Issue hier wieder auf. Also manche machen ja ggf. manuell einfach mal nen "apt update && apt upgrade". Das da dann iGotify "hängen bleibt" schaut ja keiner nach.

**Comment by androidseb25** [comment]
Ok bis jetzt nicht mitbekommen, hab das ja momentan mit der neuen Version in meiner Testumgebung laufen und da hatte ich vor kurzem auch updates gemacht und das hat ohne probleme gefunkt mmmh :/ 

Naja aber mit dem Restart sollte das wiederum auch gefixed werden, den sobald der Service tot ist wird der dann nach den angegebenen Sekunden neustartet

**Comment by nicedevil007** [comment]
könnt man ja in dem wiki artikel miteintragen ;)

übrigens, hatte dir noch 2 kleine änderungen geschickt, gaaaaaaaaaaanz unten hatte ich irgendwo service falsch geschrieben und dann die sache mit dem prompt wo der user was eingeben soll (war in ner mail an dich damals drin)
