### ISSUE TITLE
No Sound and no notification

### ISSUE THREAD

**Issue by KxmischerLasse** [androidseb25/iGotify-Notification-Assistent#41]
https://cdn.fynncraft.de/uploads/Lasse/69abf65e-7f3e-447f-b155-ccae22e9abe7.png

When I send a notification, I do not receive a notification on my iphone. And on my iPhone i can See also the notifications in the App.

I use the following command for testing

curl "https://my.domain/message?token=my.token" -F "title=my title" -F "message=my message" -F "priority=10"

**Comment by androidseb25** [comment]
Hi what does you're igotify container show and what about the app log...

Did you have a DNS Blocker that maybe block something or a firewall?

**Comment by KxmischerLasse** [comment]
I have already fixed that. 

But is it Right that i have to create a new iGotify Docker for every user with a apple device?

**Comment by androidseb25** [comment]
only today no longer from tomorrow see #35 here
