### ISSUE TITLE
[BUG] Kryptische Push-Notifications nach Update der App

### ISSUE THREAD

**Issue by paranoyd1988** [androidseb25/iGotify-Notification-Assistent#42]
**Describe the bug**
Nach dem Update der App auf Version 1.2, sowie dem damit nötigen Update des iGotify-Containers werden Push-Nachrichten nur noch kryptisch versendet. Sowohl im Log des Containers als auch in der App selbst, werden die Nachrichten korrekt anzeigt.

**Screenshots**
![IMG_1511](https://github.com/androidseb25/iGotify-Notification-Assistent/assets/161680652/a317c9cd-4dce-4df5-9992-92352836906a)

![IMG_1512](https://github.com/androidseb25/iGotify-Notification-Assistent/assets/161680652/8f424783-3573-49c1-9625-d095500dd353)

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro 
 - OS: iOS 17.3.1
 - App Version: 1.2 (19)
 - Server Version: 2.4.0
 - API Server Version: 1.2.0.0

**Comment by androidseb25** [comment]
kannst du mir mal einen log an igotify@secntfy.app schicken, damit ich mir diesen mal anschauen kann?

**Comment by paranoyd1988** [comment]
Habe ich dir geschickt

**Comment by androidseb25** [comment]
Problem hat sich erledigt nach neuinsatllation der App sowie der Container
