### ISSUE TITLE
[FEATURE REQUEST] iOS App - Notifications depending on priority

### ISSUE THREAD

**Issue by MajorTomDE** [androidseb25/iGotify-Notification-Assistent#45]
Hey,

at the moment it's only possible to customize the notifications by priorities with colors.

Would it also be possible to do more here?

e.g.
priority 0 --> no tone or notifications.  Only visible in app
priority 3 --> information tone + notification
priority 8 --> warning tone + notification

BR, Tom

**Comment by nuil** [comment]
Hi @androidseb25 ,
this feature would be very nice and appreciated.
Thanks!

**Comment by androidseb25** [comment]
![Simulator Screenshot - iPhone 15 Pro - 2024-06-26 at 12 34 21](https://github.com/androidseb25/iGotify-Notification-Assistent/assets/11179091/cd34a929-95e1-43c8-bce5-7928f0b8a12b)
![Simulator Screenshot - iPhone 15 Pro - 2024-06-26 at 12 34 24](https://github.com/androidseb25/iGotify-Notification-Assistent/assets/11179091/0095f659-22fe-49b1-91fb-69b8fb06b242)
![Simulator Screenshot - iPhone 15 Pro - 2024-06-26 at 12 34 29](https://github.com/androidseb25/iGotify-Notification-Assistent/assets/11179091/76bf5f35-c9c7-4330-b615-717e5901180f)

Feature coming in v1.3

**Comment by androidseb25** [comment]
release 1.3 in review

**Comment by androidseb25** [comment]
App is now live
