### ISSUE TITLE
[BUG] keine Push Nachrichten

### ISSUE THREAD

**Issue by ThisIsBenny** [androidseb25/iGotify-Notification-Assistent#46]
**Describe the bug**
Empfange keine Push Nachrichten 

**Expected behavior**
Push Nachrichten werden zugestellt

**Screenshots**
n/a

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro
 - OS: 17.3.1 und 17.4
 - Version of Container: 1.2.0.0
 - Version of iGotify: 1.2 (19)

**Additional context**
Device Log:
`
14:05:59.599 INFO Logger.getInstance():30 - ♻️ - Initialize iGotify Logger

14:05:59.608 INFO SecNtfy.initialize():65 - ♻️ - API URL https://api.secntfy.app

14:05:59.612 INFO SecNtfy.initialize():66 - ♻️ - Bundle Group group.sr.iGotify

14:05:59.616 INFO SecNtfy.initialize():77 - PubKey: MIIBCgKCAQEA3JZEFu7MVI1u7toocYJGZC0sRW377JQuP1hF9GQ49pDhD2YZmzp/yxSY2AH4eY8AHRHpVxp1CHqx4uIQOOhMAnmWarp/BDrWUQdGLghZp2KDELX3V01jiEpInOTyT3qNwXU30A8Xli7jBBr/uCLJZMxxJWzW5NgWDzAAxsGow8dEOFYeStPEYB604ypuWdMCDpO/Bmiff5Gh9lPBGPKNSJ499HHSo2LF3Uko5dqhGE87eUlowKwkt3VSOfn39vHGYyBpmxbJO6zvey/N8/9Dsc9ch4F10cuYhkTZKuyYHONc3GlQwpjWXBP3aNj7FsEGObUP030B6n9iB0+OdarbowIDAQAB

14:05:59.620 INFO SecNtfy.initialize():78 - PrivKey: MIIEo*****P4jE=

14:05:59.623 INFO SecNtfy.configure():102 - Model: iPhone 14 Pro

14:05:59.626 INFO SecNtfy.configure():103 - OS: 17.3.1

14:05:59.628 INFO SecNtfy.configure():105 - PubKey: MIIBCgKCAQEA3JZEFu7MVI1u7toocYJGZC0sRW377JQuP1hF9GQ49pDhD2YZmzp/yxSY2AH4eY8AHRHpVxp1CHqx4uIQOOhMAnmWarp/BDrWUQdGLghZp2KDELX3V01jiEpInOTyT3qNwXU30A8Xli7jBBr/uCLJZMxxJWzW5NgWDzAAxsGow8dEOFYeStPEYB604ypuWdMCDpO/Bmiff5Gh9lPBGPKNSJ499HHSo2LF3Uko5dqhGE87eUlowKwkt3VSOfn39vHGYyBpmxbJO6zvey/N8/9Dsc9ch4F10cuYhkTZKuyYHONc3GlQwpjWXBP3aNj7FsEGObUP030B6n9iB0+OdarbowIDAQAB

14:05:59.631 INFO SecNtfy.configure():106 - PrivKey: MIIEo*****P4jE=

14:05:59.735 VERBOSE AppDelegate.application():84 - APNs token retrieved: 32 bytes

14:05:59.741 VERBOSE AppDelegate.application():87 - The token: 610CD*****66911

14:05:59.744 INFO SecNtfy.setApnsToken():132 - 610CD*****66911

14:06:01.229 INFO SecNtfy.getInstance():43 - ♻️ - instance init

14:06:01.416 ERROR SecNtfy.PostDevice():159 - ♻️ - Optional("Device successfully created!") Optional("NTFY-DEVICE-OdJB1mdc2Q4qro4HhXwZgtcJL4pvXG8RtrA76OkT9KGIfe64VbOojtl") nil

14:06:01.425 VERBOSE Functions.sendTokenToSecNtfy():242 - registration token: NTFY-DEVICE-OdJB1mdc2Q4qro4HhXwZgtcJL4pvXG8RtrA76OkT9KGIfe64Vb....

18:47:56.668 INFO Logger.getInstance():30 - ♻️ - Initialize iGotify Logger

18:47:56.674 INFO SecNtfy.initialize():65 - ♻️ - API URL https://api.secntfy.app

18:47:56.677 INFO SecNtfy.initialize():66 - ♻️ - Bundle Group group.sr.iGotify

18:47:56.681 INFO SecNtfy.initialize():77 - PubKey: MIIBCgKCAQEA3JZEFu7MVI1u7toocYJGZC0sRW377JQuP1hF9GQ49pDhD2YZmzp/yxSY2AH4eY8AHRHpVxp1CHqx4uIQOOhMAnmWarp/BDrWUQdGLghZp2KDELX3V01jiEpInOTyT3qNwXU30A8Xli7jBBr/uCLJZMxxJWzW5NgWDzAAxsGow8dEOFYeStPEYB604ypuWdMCDpO/Bmiff5Gh9lPBGPKNSJ499HHSo2LF3Uko5dqhGE87eUlowKwkt3VSOfn39vHGYyBpmxbJO6zvey/N8/9Dsc9ch4F10cuYhkTZKuyYHONc3GlQwpjWXBP3aNj7FsEGObUP030B6n9iB0+OdarbowIDAQAB

18:47:56.685 INFO SecNtfy.initialize():78 - PrivKey: MIIEo*****P4jE=

18:47:56.689 INFO SecNtfy.configure():102 - Model: iPhone 14 Pro

18:47:56.693 INFO SecNtfy.configure():103 - OS: 17.4

18:47:56.697 INFO SecNtfy.configure():105 - PubKey: MIIBCgKCAQEA3JZEFu7MVI1u7toocYJGZC0sRW377JQuP1hF9GQ49pDhD2YZmzp/yxSY2AH4eY8AHRHpVxp1CHqx4uIQOOhMAnmWarp/BDrWUQdGLghZp2KDELX3V01jiEpInOTyT3qNwXU30A8Xli7jBBr/uCLJZMxxJWzW5NgWDzAAxsGow8dEOFYeStPEYB604ypuWdMCDpO/Bmiff5Gh9lPBGPKNSJ499HHSo2LF3Uko5dqhGE87eUlowKwkt3VSOfn39vHGYyBpmxbJO6zvey/N8/9Dsc9ch4F10cuYhkTZKuyYHONc3GlQwpjWXBP3aNj7FsEGObUP030B6n9iB0+OdarbowIDAQAB

18:47:56.700 INFO SecNtfy.configure():106 - PrivKey: MIIEo*****P4jE=

18:47:56.822 VERBOSE AppDelegate.application():84 - APNs token retrieved: 32 bytes

18:47:56.826 VERBOSE AppDelegate.application():87 - The token: 610CD*****66911

18:47:56.828 INFO SecNtfy.setApnsToken():132 - 610CD*****66911

18:47:58.285 INFO SecNtfy.getInstance():43 - ♻️ - instance init

18:47:58.338 ERROR SecNtfy.PostDevice():162 - 🔥 - Failed task Es wurde kein Server mit dem angegebenen Hostnamen gefunden.

18:47:58.348 ERROR Functions.sendTokenToSecNtfy():236 - getNtfyToken: Es wurde kein Server mit dem angegebenen Hostnamen gefunden.

18:47:58.355 ERROR Functions.sendTokenToSecNtfy():236 - getNtfyToken: Es wurde kein Server mit dem angegebenen Hostnamen gefunden.
`

**Comment by ThisIsBenny** [comment]
Ok, es war scheinbar nicht mein PiHole. Problem war der Upstream DNS den ich verwendet habe. Hatten ihn auf quad9 filtered stehen und scheinbar ist dort die Domain auf einer Blacklist. Nachdem ich auf den normalen quad9 gewechselt bin hat es geklappt

**Comment by androidseb25** [comment]
Ok alles klar kannst du mir rein zufällig die Liste sagen wo die Domain drauf ist?

**Comment by ThisIsBenny** [comment]
Die Domain ist beim DNS Provider quad9 blockiert. Hier kannst du die Domain testen: https://quad9.net/result

![image](https://github.com/androidseb25/iGotify-Notification-Assistent/assets/66417262/01e1f297-9fb0-418a-a683-bbf3cd447441)

**Comment by androidseb25** [comment]
Danke werde ich mir Mal anschauen

**Comment by androidseb25** [comment]
Kurzer Zwischenstand hab mich jetzt mit IBM in Verbindung gesetzt den Dienst zu Whitelisten

**Comment by androidseb25** [comment]
secntfy.app ist nun whitelisted 

quad9 blockt dies nun nicht mehr.
