### ISSUE TITLE
Keine Push Benachrichtigung iPhone

### ISSUE THREAD

**Issue by DarkRudolf** [androidseb25/iGotify-Notification-Assistent#48]
Hallo,

ich bekomme es leider nicht hin... 

im browser bekomme ich Benachrichtigungen. Am iPhone will es absolut nicht ich sehe die Nachrichten aber leider kein Push.

im NPM ist nur we

Log:

info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
Database is created: True
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://[::]:8080
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /app
Gotify - Url: https://gotify.***.de
Is Gotify - Url available: no
SecNtfy Server - Url: https://api.secntfy.app/api
Is SecNtfy Server - Url available: yes
Client - Token: ********
Client connecting...
Done!
Disconnection happened, type: Websocket.Client.DisconnectionInfo
warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
      Failed to determine the https port for redirect.

Log App:
16:47:49.020 INFO Logger.getInstance():30 - ♻️ - Initialize iGotify Logger

16:47:49.028 INFO SecNtfy.initialize():65 - ♻️ - API URL https://api.secntfy.app

16:47:49.034 INFO SecNtfy.initialize():66 - ♻️ - Bundle Group group.sr.iGotify

16:47:49.037 INFO SecNtfy.initialize():77 - PubKey: MIIBCgKCAQEAq3j7quS7u6oUbTgidtGYgTzIWgOSR4bLuaifWLHFSTgKwD9/fTxOLLNPrWdPRJhK+Y50tGM9kpDrfR9VOAvo5jArg3bBO4UbRfNeO8jHmg89MgBGnZjWHoKjJTzpYN4X2PjQSnBWH1oHhV84799lfNrSiim3W0+KV6ERZvAxyeOvPbdwFy5+Psn8D/fMJ92Vd7xI4Om1OPyTXGVLLCLuHDoSzC6NG7KQhYKa5URDDMPL6h4KaX9vRJ1TNwHoTvDTLfDdXSWXYkOc9Uk4DnHm9UVex8qdJ2L4Sk1RoVnHdPg5SYPbJgUS9aXjYJUdpGu5MGo2ATTARhePvz/XNmGXIwIDAQAB

16:47:49.040 INFO SecNtfy.initialize():78 - PrivKey: MIIEo*****qy5Zm

16:47:49.043 INFO SecNtfy.configure():102 - Model: iPhone 14 Pro

16:47:49.046 INFO SecNtfy.configure():103 - OS: 17.4.1

16:47:49.049 INFO SecNtfy.configure():105 - PubKey: MIIBCgKCAQEAq3j7quS7u6oUbTgidtGYgTzIWgOSR4bLuaifWLHFSTgKwD9/fTxOLLNPrWdPRJhK+Y50tGM9kpDrfR9VOAvo5jArg3bBO4UbRfNeO8jHmg89MgBGnZjWHoKjJTzpYN4X2PjQSnBWH1oHhV84799lfNrSiim3W0+KV6ERZvAxyeOvPbdwFy5+Psn8D/fMJ92Vd7xI4Om1OPyTXGVLLCLuHDoSzC6NG7KQhYKa5URDDMPL6h4KaX9vRJ1TNwHoTvDTLfDdXSWXYkOc9Uk4DnHm9UVex8qdJ2L4Sk1RoVnHdPg5SYPbJgUS9aXjYJUdpGu5MGo2ATTARhePvz/XNmGXIwIDAQAB

16:47:49.052 INFO SecNtfy.configure():106 - PrivKey: MIIEo*****qy5Zm

16:47:49.220 VERBOSE AppDelegate.application():84 - APNs token retrieved: 32 bytes

16:47:49.223 VERBOSE AppDelegate.application():87 - The token: 0ECF7*****6A885

16:47:49.226 INFO SecNtfy.setApnsToken():132 - 0ECF7*****6A885

16:47:50.642 INFO SecNtfy.getInstance():43 - ♻️ - instance init

16:47:51.076 ERROR SecNtfy.PostDevice():159 - ♻️ - Optional("Device already added") Optional("**") nil

16:47:51.084 VERBOSE Functions.sendTokenToSecNtfy():242 - registration token: **

**Comment by androidseb25** [comment]
Hi, 

Es sieht so aus als würde er deinen Gotify Server nicht finden können.

Wie hast du den Service installiert?
Als docker oder als SystemD Service?

**Comment by DarkRudolf** [comment]
Ich habe die Docker Compose genommen und von aussen ist alles erreichbar was mich wundert.

**Comment by DarkRudolf** [comment]
seltsam...

GOTIFY_SERVER_URL	10.100.0.3:8680 das stimmt soweit.
in der Firewall wird auch nix geblockt und alles ist von innen und aussen erreichbar.... was auch immer ich da verbockt habe

**Comment by androidseb25** [comment]
Schonmal über die interne IP probiert?

Vielleicht hilft das schon

**Comment by DarkRudolf** [comment]
Ja auch schon probiert :-( Von meinem iPhone gesendetAm 29.03.2024 um 18:05 schrieb Sebastian ***@***.***>:﻿
Schonmal über die interne IP probiert?
Vielleicht hilft das schon

**Comment by androidseb25** [comment]
Puuuuuhhh das wird schwer das herauszufinden warum der Container auf die URL nicht draufkommt 🤔
Das hat meistens immer was mit der Netzwerk Konfiguration zu tun.

Kommst du auf folgende Schnittstelle im Browser ran?

https://<urlgotify>/version

**Comment by DarkRudolf** [comment]
nur wenn ich die ip angebe mit port und http

{"version":"2.4.0","commit":"97f180b65091fc6ca313d29dfc5b559aa8cd9465","buildDate":"2023-09-17-08:24:00"}

**Comment by androidseb25** [comment]
Da haben wirs doch irgewndwas stimmt bei deinem Webproxy nicht
wenn es bei der ip klappt und nicht bei der domain

**Comment by DarkRudolf** [comment]
Achse von aussen bekomme ich auch 

auch die version

https://gotify.**.de/version <https://gotify..de/version>

**Comment by DarkRudolf** [comment]
da fällt mir ein könnte es an Cloudflare liegen?

**Comment by androidseb25** [comment]
Ok gut dann ist es nicht das routing wenn es klappt

Keine Ahnung kann durch aus sein....

**Comment by DarkRudolf** [comment]
jetzt kommt im log

Disconnection happened, type: Websocket.Client.DisconnectionInfo
warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
      Failed to determine the https port for redirect.

**Comment by DarkRudolf** [comment]
Habe den Fehler gefunden…

Cloudflare hat einen Bot erkannt und alles geklockt!! Hat also alles funktioniert mann bin ich blöd aber dennoch danke für die Hilfe.

**Comment by androidseb25** [comment]
Ok warum haben die das als bot erkannt 🤔

**Comment by DarkRudolf** [comment]
ich sende dir mal das event log vielleicht hilft es.

{
  "action": "managed_challenge",
  "clientASNDescription": "HETZNER-AS",
  "clientAsn": "24940",
  "clientCountryName": "DE",
  "clientIP": „Meine Server IP",
  "clientRequestHTTPHost": „gotify.**.de",
  "clientRequestHTTPMethodName": "GET",
  "clientRequestHTTPProtocol": "HTTP/1.1",
  "clientRequestPath": "/stream",
  "clientRequestQuery": "?token=***",
  "datetime": "2024-03-29T19:29:57Z",
  "rayName": "86c2458d7f9a5d8e",
  "ruleId": "bot_fight_mode",
  "rulesetId": "",
  "source": "botFight",
  "userAgent": "",
  "matchIndex": 0,
  "metadata": [],
  "sampleInterval": 1
}


{
  "action": "managed_challenge",
  "clientASNDescription": "HETZNER-AS",
  "clientAsn": "24940",
  "clientCountryName": "DE",
  "clientIP": „Server IP",
  "clientRequestHTTPHost": „gotify.**.de",
  "clientRequestHTTPMethodName": "GET",
  "clientRequestHTTPProtocol": "HTTP/1.1",
  "clientRequestPath": "/",
  "clientRequestQuery": "",
  "datetime": "2024-03-29T19:29:57Z",
  "rayName": "86c2458b6e129f1f",
  "ruleId": "bot_fight_mode",
  "rulesetId": "",
  "source": "botFight",
  "userAgent": "",
  "matchIndex": 0,
  "metadata": [],
  "sampleInterval": 1
}

**Comment by androidseb25** [comment]
Ok danke ich schau mal ob man das irgendwie abstellen kann

**Comment by androidseb25** [comment]
konnte nichts herausfinden was ich dagegen machen kann schließe mal den issue
