### ISSUE TITLE
Keine IPhone Push Notification

### ISSUE THREAD

**Issue by VolleyTom8** [androidseb25/iGotify-Notification-Assistent#5]
Hallo,
Ich habe heute den Docker Container (Gotify + iGotify-Notification) ausgerollt und dieser funktioniert auch einwandfrei, soweit ich das feststellen kann. Auch die Handy-App konnte ich Installieren und mich einloggen. Jedoch funktioniert die PUSH-Notifikation nicht, wenn ich es manuell aktualisiere in der App, dann erscheinen die Nachrichten.
   _App-Version: 1.0.3 (10)
   Server Version: 2.4.0
   API Server Version: 1.0.0.7
   IPhone 14
   IOS 17.2_
lG Tom

**Comment by androidseb25** [comment]
Ich schau mir das Problem an

**Comment by GieGit** [comment]
Hallo, @androidseb25  
ich habe die gleiche Situation mit dem Iphone15.
LG

**Comment by androidseb25** [comment]
Erste Frage @VolleyTom8 & @GieGit ,
nutzt ihr einen NGINX Proxy Manager?
Wenn ja aktiviert dort bitte den Websocket Support.

Falls nicht schaut mal bitte in die Logs des Notification Assistent Containers mit `docker Logs <containerid>` falls er irgendwas sagt das er den websocket nicht verbinden kann, habt ihr das Problem gefunden.

**Comment by VolleyTom8** [comment]
Hallo,Also ich habe die WebSocket-Support aktiv:Gotify:IGotify: Und hier der Log des ***@***.***:~# docker logs 2cb37b5bf6cdinfo: Quartz.Core.SchedulerSignalerImpl[0]      Initialized Scheduler Signaller of type: Quartz.Core.SchedulerSignalerImplinfo: Quartz.Core.QuartzScheduler[0]      Quartz Scheduler createdinfo: Quartz.Core.QuartzScheduler[0]      JobFactory set to: Quartz.Simpl.MicrosoftDependencyInjectionJobFactoryinfo: Quartz.Simpl.RAMJobStore[0]      RAMJobStore initialized.info: Quartz.Impl.StdSchedulerFactory[0]      Quartz Scheduler 3.8.0.0 - 'QuartzScheduler' with instanceId 'NON_CLUSTERED' initializedinfo: Quartz.Impl.StdSchedulerFactory[0]      Using thread pool 'Quartz.Simpl.DefaultThreadPool', size: 10info: Quartz.Impl.StdSchedulerFactory[0]      Using job store 'Quartz.Simpl.RAMJobStore', supports persistence: False, clustered: FalseFile is created.Connecting to serverClient - Token: XXXXXXXXXXGotify - Url: ws://gotify/stream?token=XXXXXXXXXXXXinfo: Microsoft.Hosting.Lifetime[14]      Now listening on: http://[::]:8080info: Microsoft.Hosting.Lifetime[0]      Application started. Press Ctrl+C to shut down.info: Microsoft.Hosting.Lifetime[0]      Hosting environment: Productioninfo: Microsoft.Hosting.Lifetime[0]      Content root path: /appinfo: Quartz.Core.QuartzScheduler[0]      Scheduler QuartzScheduler_$_NON_CLUSTERED started.Connected!warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]      Failed to determine the https port for redirect.TOKEN: d0LuOj_XXXXXXXXXXXXXXXXXXXDEVICE: iPhone 14 Mehr habe ich nicht drinnen, die Token habe ich durch XXX erstetzt.lG Tom Von: SebastianGesendet: Montag, 18. Dezember 2023 07:56An: androidseb25/iGotify-Notification-AssistentCc: VolleyTom8; MentionBetreff: Re: [androidseb25/iGotify-Notification-Assistent] Keine IPhone Push Notification (Issue #5) Erste Frage @VolleyTom8 & @GieGit ,nutzt ihr einen NGINX Proxy Manager?Wenn ja aktiviert dort bitte den Websocket Support.Falls nicht schaut mal bitte in die Logs des Notification Assistent Containers mit docker Logs <containerid> falls er irgendwas sagt das er den websocket nicht verbinden kann, habt ihr das Problem gefunden.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by androidseb25** [comment]
> Hallo, Also ich habe die WebSocket-Support aktiv:Gotify:IGotify: Und hier der Log des ``` ***@***.***:~# docker logs 2cb37b5bf6cd info: Quartz.Core.SchedulerSignalerImpl[0] Initialized Scheduler Signaller of type: Quartz.Core.SchedulerSignalerImplinfo: Quartz.Core.QuartzScheduler[0] Quartz Scheduler createdinfo: Quartz.Core.QuartzScheduler[0 JobFactory set to: Quartz.Simpl.MicrosoftDependencyInjectionJobFactoryinfo: Quartz.Simpl.RAMJobStore[0] RAMJobStore initialized. info: Quartz.Impl.StdSchedulerFactory[0] Quartz Scheduler 3.8.0.0 - 'QuartzScheduler' with instanceId 'NON_CLUSTERED' initializedinfo: Quartz.Impl.StdSchedulerFactory[0] Using thread pool 'Quartz.Simpl.DefaultThreadPool', size: 10 info: Quartz.Impl.StdSchedulerFactory[0] Using job store 'Quartz.Simpl.RAMJobStore', supports persistence: False, clustered: False File is created.Connecting to serverClient - Token: XXXXXXXXXXGotify - Url: ws://gotify/stream?token=XXXXXXXXXXXX info: Microsoft.Hosting.Lifetime[14] Now listening on: http://[::]:8080info: Microsoft.Hosting.Lifetime[0] Application started. Press Ctrl+C to shut down.info: Microsoft.Hosting.Lifetime[0] Hosting environment: Productioninfo: Microsoft.Hosting.Lifetime[0]  Content root path: /appinfo: Quartz.Core.QuartzScheduler[0]  Scheduler QuartzScheduler_$_NON_CLUSTERED started. Connected! warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3] Failed to determine the https port for redirect. TOKEN: d0LuOj_XXXXXXXXXXXXXXXXXXXDEVICE: iPhone 14 ``` Mehr habe ich nicht drinnen, die Token habe ich durch XXX erstetzt.lG Tom

ok das sieht erstmal alles sauber aus

kann es sein das bei dir ein DNS Blocker oder ähnliches was wegblockt?
Was kommt für ein Text im log wenn du eine Benachrichtigung bekommst?

**Comment by VolleyTom8** [comment]
Hallo,
Ich habe keinen DNS Blocker am Handy, daher glaube ich nicht dass es daran liegt und wenn der "manuelle Refresh" funktioniert, kann es wohl nicht daran liegen oder geht das über einen ganz anderen Weg?
LG Tom

**Comment by christophs91** [comment]
Hi, ich hatte das gleiche Problem. Bei mir hat jetzt ein Neustart des Docker Containers geholfen, warum auch immer. Jetzt tauchen die Notifications auf.

iPhone 13 mini
iOS 17.2
App-Version: 1.0.3 (10)
Server Version: 2.4.0
API Server Version: 1.0.0.7

**Comment by androidseb25** [comment]
> Hallo, Ich habe keinen DNS Blocker am Handy, daher glaube ich nicht dass es daran liegt und wenn der "manuelle Refresh" funktioniert, kann es wohl nicht daran liegen oder geht das über einen ganz anderen Weg? LG Tom

Der DNS Blocker liegt in den meisten fällen nicht auf dem handy sondern im Netzwerk (AdGuard, PiHole).

Aber laut dem Log gibt es ja ein device token was sagt das er sich mit Firebase gesynct hat. jetzt ist nur noch das problem am container :/ mach einfach mal einen restart so wie es @christophs91 gemacht hat, vllt hilft das schon.

**Comment by VolleyTom8** [comment]
> Hi, ich hatte das gleiche Problem. Bei mir hat jetzt ein Neustart des Docker Containers geholfen, warum auch immer. Jetzt tauchen die Notifications auf.

Ich habe jetzt auch restartet die beiden Docker Container, jedoch funktioniert es bei mir immer noch nicht.

**Comment by GieGit** [comment]
@androidseb25  
Ich habe die Adressen aus deiner Anleitung im Adblocker freigegeben (war nur eine wirklich auf einer blockliste) 
und den Stack neu aufgebaut, aber gepusht werden die Nachrichten immer noch nicht. 
Wenn ich die App öffne sind sie aber da.

**Comment by androidseb25** [comment]
> @androidseb25  
> 
> Ich habe die Adressen aus deiner Anleitung im Adblocker freigegeben (war nur eine wirklich auf einer blockliste) 
> 
> und den Stack neu aufgebaut, aber gepusht werden die Nachrichten immer noch nicht. 
> 
> Wenn ich die App öffne sind sie aber da. 

Hast du die App nochmal neu eingerichtet nach dem Neustart und der Freigabe?

**Comment by GieGit** [comment]
Ich habe den Docker-Stack neu gestartet, die App auf dem Iphone gelöscht , neu installiert und eingerichtet. Aber keine Veränderung, Nachrichten werden nicht gepusht, öffne ich die App, dann sind sie aber da.

**Comment by androidseb25** [comment]
@GieGit 

Führe mal folgendes aus und beobachte den log im igotify container was dort drin steht bzw passiert und poste den für mich bitte. Die Tokens kannst du dann raus X beim posten des logs.

`curl "http://<gotify-addresse>/message?token=<ApplicationToken>" -F "title=Das ist ein Test" -F "message=das ist eine Testnachricht von einem curl Aufruf" -F "priority=1";`

**Comment by GieGit** [comment]
@androidseb25 Hallo Sebastian, 
die Nachrichten kommen sauber an, wenn ich die App öffne sind sie da

023-12-18T15:40:00.008774795Z info: iGotify_Notification_Assist.GotifySocketJob[0]
2023-12-18T15:40:00.008837625Z       WS is closed, OMG dude, come on reconnect now!
2023-12-18T15:40:00.008932589Z Connecting to server
2023-12-18T15:40:00.008942834Z Client - Token: XXXXXXXXXXXXXXXXX
2023-12-18T15:40:00.008947336Z Gotify - Url: ws://gotify/stream?token=XXXXXXXXXXXXXXXX
2023-12-18T15:40:00.010209680Z Unable to Connect to WS or WS connection aborted
2023-12-18T15:40:00.010286708Z    at System.Net.WebSockets.WebSocketHandle.ValidateResponse(HttpResponseMessage response, String secValue)
2023-12-18T15:40:00.010304925Z    at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, HttpMessageInvoker invoker, CancellationToken cancellationToken, ClientWebSocketOptions options)
2023-12-18T15:40:00.010321505Z    at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, HttpMessageInvoker invoker, CancellationToken cancellationToken)
2023-12-18T15:40:00.010341046Z    at iGotify_Notification_Assist.GotifySocketService.Start() in /src/GotifySocketService.cs:line 82

**Comment by androidseb25** [comment]
> @androidseb25 Hallo Sebastian, die Nachrichten kommen sauber an, wenn ich die App öffne sind sie da
> 
> 023-12-18T15:40:00.008774795Z info: iGotify_Notification_Assist.GotifySocketJob[0] 2023-12-18T15:40:00.008837625Z WS is closed, OMG dude, come on reconnect now! 2023-12-18T15:40:00.008932589Z Connecting to server 2023-12-18T15:40:00.008942834Z Client - Token: XXXXXXXXXXXXXXXXX 2023-12-18T15:40:00.008947336Z Gotify - Url: ws://gotify/stream?token=XXXXXXXXXXXXXXXX 2023-12-18T15:40:00.010209680Z Unable to Connect to WS or WS connection aborted 2023-12-18T15:40:00.010286708Z at System.Net.WebSockets.WebSocketHandle.ValidateResponse(HttpResponseMessage response, String secValue) 2023-12-18T15:40:00.010304925Z at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, HttpMessageInvoker invoker, CancellationToken cancellationToken, ClientWebSocketOptions options) 2023-12-18T15:40:00.010321505Z at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, HttpMessageInvoker invoker, CancellationToken cancellationToken) 2023-12-18T15:40:00.010341046Z at iGotify_Notification_Assist.GotifySocketService.Start() in /src/GotifySocketService.cs:line 82

Dein Websocket kann sich nicht verbinden. 

Das heißt deine URL ist fehlerhaft!

Nimmst du die compose aus der Anleitung oder hast du diese angepasst?

**Comment by GieGit** [comment]
Ja das habe ich genommen, da ich das als Portainer Stack gemacht habe, ist der name des Containers ein anderer 
in der anleitung hast du 
    - GOTIFY_SERVER_URL="http://gotify"  # default container name from gotify server
 geschrieben.  da war ein fehler bei mir.
Mein Container heisst im Poertainer stack aber gotifyintern-gotify-1, wenn ich den mit docker ps anzeigen lasse. 
wenn ich die Url auf 
- GOTIFY_SERVER_URL="http://gotifyintern-gotify-1"  # default container name from gotify server
anpasse, geht es aber auch nicht

**Comment by androidseb25** [comment]
> Ja das habe ich genommen, da ich das als Portainer Stack gemacht habe, ist der name des Containers ein anderer 
> 
> in der anleitung hast du 
> 
>     - GOTIFY_SERVER_URL="http://gotify"  # default container name from gotify server
> 
>  geschrieben.  da war ein fehler bei mir.
> 
> Mein Container heisst im Poertainer stack aber gotifyintern-gotify-1, wenn ich den mit docker ps anzeigen lasse. 
> 
> wenn ich die Url auf 
> 
> - GOTIFY_SERVER_URL="http://gotifyintern-gotify-1"  # default container name from gotify server
> 
> anpasse, geht es aber auch nicht
> 

Der Name `gotify` ist der DNS Name innerhalb des stacks deswegen ist die URL `http://gotify` korrekt

Und der Container Name hat nichts mit den Namen innerhalb des stacks zu tun.

**Comment by androidseb25** [comment]
> > Hi, ich hatte das gleiche Problem. Bei mir hat jetzt ein Neustart des Docker Containers geholfen, warum auch immer. Jetzt tauchen die Notifications auf.
> 
> 
> 
> Ich habe jetzt auch restartet die beiden Docker Container, jedoch funktioniert es bei mir immer noch nicht.

Bei dir gilt das selbe passt das docker compose file?

**Comment by christophs91** [comment]
> > > Hi, ich hatte das gleiche Problem. Bei mir hat jetzt ein Neustart des Docker Containers geholfen, warum auch immer. Jetzt tauchen die Notifications auf.
> > 
> > 
> > Ich habe jetzt auch restartet die beiden Docker Container, jedoch funktioniert es bei mir immer noch nicht.
> 
> Bei dir gilt das selbe passt das docker compose file?

Ich habe das compose file 1:1 übernommen. Nur das Default Passwort und nach einem einmaligen Login mit der iGotify App den Client Token in der Compose Datei angepasst.

**Comment by androidseb25** [comment]
Gehst du über den admin User in der App oder über einen neu erstellten? @christophs91

**Comment by androidseb25** [comment]
Hat GitHub dich jetzt getriggert? Bei dir hat es doch funktioniert richtig?
Meinte eigentlich @VolleyTom8 damit

**Comment by VolleyTom8** [comment]
Ich verwende einen anderen User der Admin ist.Am 18.12.2023 um 22:38 schrieb Sebastian ***@***.***>:﻿
Gehst du über den admin User in der App oder über einen neu erstellten? @christophs91

**Comment by christophs91** [comment]
> Hat GitHub dich jetzt getriggert? Bei dir hat es doch funktioniert richtig? Meinte eigentlich @VolleyTom8 damit

Bei mir klappt es. Ich nutze den Admin User derzeit.

**Comment by androidseb25** [comment]
> Ich verwende einen anderen User der Admin ist.Am 18.12.2023 um 22:38 schrieb Sebastian ***@***.***>:﻿
> 
> Gehst du über den admin User in der App oder über einen neu erstellten? @christophs91
> 
> 
> 
> —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

Ok interessant bist jetzt der zweite der einen anderen user nutzt als den admin user. Momentan geh ich davon aus das gotify dort nen problem hat. Aber ich probiere es selber nochmal.

**Comment by christophs91** [comment]
Ich habe es gerade testweise mit einem normalen Users statt eines Admin Users probiert. Das klappt allerdings auch.

**Comment by androidseb25** [comment]
> Ich habe es gerade testweise mit einem normalen Users statt eines Admin Users probiert. Das klappt allerdings auch. 

Ok Danke fürs Testen, das ist mal sehr interessant 🧐

**Comment by VolleyTom8** [comment]
> Hat GitHub dich jetzt getriggert? Bei dir hat es doch funktioniert richtig? Meinte eigentlich @VolleyTom8 damit

Ich habe das Problem gefunden, ich hatte beim "IGOTIFY_CLIENT_TOKEN" den Token des Admins verwendet, mit dem Token des anderen Users funktioniert es jetzt. D.h. aber auch, wenn ich mehrerer User habe, dann muss ich für jeden einen eigenen Docker Container für IGotifyNotification ausrollen und für jeden ein eigenes URL machen, oder sehe ich das falsch?

Trotzdem Danke für die Hilfe.
Tom

**Comment by androidseb25** [comment]
> > Hat GitHub dich jetzt getriggert? Bei dir hat es doch funktioniert richtig? Meinte eigentlich @VolleyTom8 damit
> 
> Ich habe das Problem gefunden, ich hatte beim "IGOTIFY_CLIENT_TOKEN" den Token des Admins verwendet, mit dem Token des anderen Users funktioniert es jetzt. D.h. aber auch, wenn ich mehrerer User habe, dann muss ich für jeden einen eigenen Docker Container für IGotifyNotification ausrollen und für jeden ein eigenes URL machen, oder sehe ich das falsch?
> 
> Trotzdem Danke für die Hilfe. Tom

Ja du siehst das richtig, es gibt halt bei Gotify keine andere Möglichkeit.
