### ISSUE TITLE
[BUG] All notifications are 0s ago

### ISSUE THREAD

**Issue by nicklutt** [androidseb25/iGotify-Notification-Assistent#53]
**Describe the bug**
There is a discrepancy in the timestamp display for notifications in the app. Every notification, regardless of when it was actually received, is displayed as "0 seconds ago". This issue is not observed on the Gotify server, where the correct time is shown.

**Expected behavior**
The app should correctly display the time elapsed since each notification was received, consistent with the time displayed on the Gotify server. Each notification's timestamp should accurately reflect how long ago it was received, rather than showing "0 seconds ago."

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [iPhone14]
 - OS: [iOS17.4.1]
 - Version of Container [latest]
 - Version of iGotify [latest

**Comment by androidseb25** [comment]
What timezone or better what time format do you have?

The reason why he write 0s is that he can't parse the date for some reasons 🤨

**Comment by nicklutt** [comment]
TZ: Europe/amsterdam

**Comment by androidseb25** [comment]
Hi, i've testet now on my second iphone with all the settings and created a Gotify and iGotify instance with TZ Amsterdam

and i can't reproduce the problem :/ everything is working as expected. Take a look at the sdcreenshots

![IMG_0011](https://github.com/androidseb25/iGotify-Notification-Assistent/assets/11179091/a58cbded-9318-4022-81c8-18b36ccc7cad)
![IMG_0013](https://github.com/androidseb25/iGotify-Notification-Assistent/assets/11179091/44dcbcaf-31f6-4c76-9ccd-5f22a72510de)
![Schermafbeelding 2024-04-18 om 08 07 39](https://github.com/androidseb25/iGotify-Notification-Assistent/assets/11179091/37cc92f9-b3f8-4cdb-b63a-29e36f198da6)

**Comment by nicklutt** [comment]
I redeployed the containers and reconnected iGotify, and I see a normal time in the app ✌️

Strange,
But I didn't change anything in config or compose. But it's fixed, so you can close the bug ✅

**Comment by androidseb25** [comment]
ok really strange 😅

**Comment by nicklutt** [comment]
But thank you. I bought you a coffee ☕️

**Comment by androidseb25** [comment]
ok thx, not for that 🙏🏼

**Comment by androidseb25** [comment]
Hi, no both thinks don't related to each other, the 10s issue is only for information purpose, because sometimes the websocket connection can be lost and he is trying to reconnect. You can read about here #50 and the release for that is 1.2.0.3.

The seconds issue is a bit difficult to fix, because the timestamps that i parse are all correct. the only thing that can be the problem is the timelineview from swiftui, until now i can't reproduce this issue :/

**Comment by nicklutt** [comment]
> Hello @androidseb25 !
> 
> 
> 
> I am facing the same issue with the 0s ago for each message. 
> 
> ![IMG_7056](https://github.com/androidseb25/iGotify-Notification-Assistent/assets/17313213/f6214799-3f9a-4e9c-a594-6ecd3744c755)
> 
> 
> 
> Both gotify and igotify have the same time zone America/Chicago. 
> 
> 
> 
> Restarts, redeployment, and reconnection of docker containers, and the iOS app won't work. 
> 
> 
> 
> Also I noticed an error igotify container logs about connection to the gotify server failed, retrying in 10 seconds. And yet, I can see a new notification in the app.
> 
> Maybe these are two related issues, or maybe they are not :)
> 
> 
> 
> I hope you can help me with that!
> 
> 
> 
> Thanks!

My fix: after I removed the containers (gotify and iGotify). And redeployed the docker-compose it was fixed.

**Comment by androidseb25** [comment]
Ok thanks, I will try to fix it with this Informations

**Comment by androidseb25** [comment]
i think i have fixed this bug with you're informations
the fix will be a part of version 1.3

**Comment by androidseb25** [comment]
> @androidseb25 is there a link to the iOS app? I would like to contribute:)

No at the moment, only for the language file

**Comment by androidseb25** [comment]
release 1.3 in review

**Comment by androidseb25** [comment]
App is now live

**Comment by androidseb25** [comment]
perfect

**Comment by Tigge11** [comment]
Hey,
Ich habe leider das gleiche Problem, dass die Zeit immer vor 0s anzeigt.
Ich habe versucht die TZ rein und rauszunehmen aber sehe keinen Unterschied.

Ich benutze Unraid und habe dort Gotify und IGotify laufen.
Bisher lief immer alles super.
Kann nicht sagen, wie lange der Fehler schon auftritt.

Die Daten vom Server sehen so aus:
"date": "2024-07-30T12:40:28.056306176+02:00"

**Comment by androidseb25** [comment]
> Hey,
> 
> Ich habe leider das gleiche Problem, dass die Zeit immer vor 0s anzeigt.
> 
> Ich habe versucht die TZ rein und rauszunehmen aber sehe keinen Unterschied.
> 
> 
> 
> Ich benutze Unraid und habe dort Gotify und IGotify laufen.
> 
> Bisher lief immer alles super.
> 
> Kann nicht sagen, wie lange der Fehler schon auftritt.
> 
> 
> 
> Die Daten vom Server sehen so aus:
> 
> "date": "2024-07-30T12:40:28.056306176+02:00"
> 
> 
> 
> EDIT:
> 
> Ich habe gerade gemerkt Unraid setzt die Zeit automatisch auf Europe/Berlin und Ich finde keine Option das Unraid die Variable nicht setzt

Hi, hast du schon probiert UTC als variable einzutragen? Denn Gotify nutzt UTC als Zeitzone

**Comment by Tigge11** [comment]
Okay Jetzt funktioniert es wieder.
Vielen Dank für die schnelle Hilfe.

Aber es hat denke Ich auch schonmal mit der Lokalen Zeitzone geklappt.

Vielleicht wäre das eine gute Standardeinstellung in der Unraid App/Container wenn du den administrieren und ändern kannst.

**Comment by androidseb25** [comment]
Auf gotify hab ich leider keinen Einfluss nur auf iGotify und da ich UnRaid nicht nutze und das auch nicht dafür bereitgestellt hatte, kann ich da leider nichts machen

**Comment by RichKidsDev** [comment]
Ich habe die Vorlage zu CA von Unraid hinzugefügt und bearbeite diese noch.
