### ISSUE TITLE
No Connection to gotify/server-arm64 Container

### ISSUE THREAD

**Issue by DonPablo1010** [androidseb25/iGotify-Notification-Assistent#55]
**Describe the bug**
I'm having trouble getting igotify to work with gotify/server-arm64. The igotify container isn't able to establish a connection with the gotify container using this image. On another instance running the regular gotify image, everything works fine.

**Expected behavior**
It would be great if arm64 support were available. Does igotify also require a separate image for that?

**Screenshots**

**Smartphone (please complete the following information):**
 - Version of Container [e.g. 1.0.0.7]
 - Version of iGotify [e.g. 1.0.5]

**Additional context**

**Comment by androidseb25** [comment]
Can you give me please some logs?
What version do you use?

The assistant works with arm64 because it's a multiplatform image that includes arm/arm64/amd64.

If there are some trouble with the gotify image please consider the dev of gotify, I'm only the guy who developed an bridge for iOS

**Comment by DonPablo1010** [comment]
Database is created: True
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://[::]:8080
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /app
warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
      Failed to determine the https port for redirect.


This is the log of the igotify container. Is the problem maybe relatet to nginx proxy manager? Because on the setup working i use the one from synology and here where this happens it ist nginx.

**Comment by androidseb25** [comment]
that's all? when not please provide the me the full log, the domain and token etc can be removed.
nothing like 

`Gotify - Url: http://xyz.xyz`
`Is Gotify - Url available: yes/no`
`SecNtfy Server - Url: http://xyz.xyz`
`Is SecNtfy Server - Url available: yes/no`
`Client - Token: XXXXX`

**Comment by androidseb25** [comment]
did you can see the swagger api when you open you're `iospush.mydomain.ch` domain?

when yes please try to send a test message with the last endpoint in the list. you need the notification token starting with NTFY-DEVICE-. You will find it in the app, when you everything setuped

**Comment by DonPablo1010** [comment]
Sending the testmessage to the device over Swagger worked. 

The Container Log says still:
Gotify Server is not available try to reconnect in 10s

It has lost the Websocket connection as i sendt the first Testnotification and connectioncan no longer be established to the gotify server from igotify container... But i can reached the server over push.mydomain.ch without a problem with a browser...

**Comment by androidseb25** [comment]
can you test if the domain is reachable from inside the iGotify Notification Container?

**Comment by DonPablo1010** [comment]
Yes, got it!! Sorry, you can close this issue. How could i be so dumb. It was ufw. But i was so shure that i did the disable while testing. 

If any one wonders how to test if a host is reachable from inside the container, here is how to:

`docker exec -ti <ContainerName> timeout 3 /bin/bash -c "echo > /dev/tcp/push.yourdomain.ch/443 >& /dev/null" && echo "ok" || echo "nok"`

As soon as i disable ufw and ran the cmd above i got "ok"... Now i allowed docker networkbridge ip range to any app 'Nginx Full' and the containers can connect over the reverse proxy.

**Comment by androidseb25** [comment]
Ok

Nice, ufw I also sometimes forget 😅
