### ISSUE TITLE
Push notification doesn't work

### ISSUE THREAD

**Issue by lucafolin** [androidseb25/iGotify-Notification-Assistent#58]
I have iGotify installed in a docker container and when I star the container everything seems to work fine and push notifications arrives at IOS, after some while all notifications don't arrive any more.
This is my container log ...

![image](https://github.com/androidseb25/iGotify-Notification-Assistent/assets/9470145/706bc793-1037-413c-91a0-1dd6febacbe9)

It seems a websocket disconnection issue ??!!

I have an haproxy as reverse proxy in the middle.
It works, the push messages arrives when I restart the container. Is it something related with websocket timeout or somethinig like this ?
This is my haproxy frontend setting for websocket

#websocket connection
http-request set-header Upgrade %[req.hdr(Upgrade)]
http-request set-header Connection %[req.hdr(Connection)]
http-request set-header Host %[req.hdr(host)]
http-request add-header Cache-Control "no-cache" if { hdr(Connection) -i Upgrade }
http-request add-header Cache-Control "no-store" if { hdr(Connection) -i Upgrade }

**Comment by androidseb25** [comment]
Hi did you have the latest version installed?

And maybe it’s a problem with the timeout settings of you're HAProxy, i don't use HA and i can't test it.

**Comment by lucafolin** [comment]
I probably didn't update to the latest version. Now it seems to have been working fine for 1 day.

**Comment by androidseb25** [comment]
perfect i close the issue when you have an problem with that again, please reopen the Issue
