### ISSUE TITLE
[Feature Request] Vorschläge

### ISSUE THREAD

**Issue by Nollknolle** [androidseb25/iGotify-Notification-Assistent#6]
Hey,
ich finde die App super, vielen Dank :)

Ich habe nur 1-2 Vorschläge die super wären für mich und vlt allen anderen:
- Unter "Mitteilungen" eine Anzeige in welchem Channel es gesendet wurde. Wenn ich zum Beispiel über NodeJS eine Nachricht sende und einen anderen Title wähle wird der App-Name durch den Title ersetzt und nicht ob es aus dem Channel "Uptime Kuma" oder wie bei mir "RT37" kommt.
![](http://i.nlmyr.de/u/vgT2Y9.png)

- ~Zu lange Titel werden abgekürzt in der App und man kann nicht mehr sehen, was dort steht.
![](http://i.nlmyr.de/u/ZBpLs4.png)~

- ~Zu Punkt 2 auch in der Mitteilung eine Anzeige aus welchem Channel/App es kommt.~

**Comment by Nollknolle** [comment]
Zu Punkt 2:
Witzig ist wenn ich das iPhone einmal drehe auf quer wird der Titel größentechnisch angepasst und wenn ich wieder hochkant gehe dann bleibt er ausgeschrieben.

**Comment by androidseb25** [comment]
Punkt 1 in der Weboberfläche hat man auch nur das Icon für die Unterscheidung
Es wird aber später einen Applicationfilter geben wo man dann speziell Filtern kann.

Punkt 2 ich kann den Titel natürlich noch als separate Zeile ausgeben.

> Zu Punkt 2:
Witzig ist wenn ich das iPhone einmal drehe auf quer wird der Titel größentechnisch angepasst und wenn ich wieder hochkant gehe dann bleibt er ausgeschrieben.

Das ist nen Bug unter iOS, normalerweise aktualisiert der das und es wird wieder mit Punkten angezeigt

**Comment by Nollknolle** [comment]
> Punkt 1 in der Weboberfläche hat man auch nur das Icon für die Unterscheidung Es wird aber später einen Applicationfilter geben wo man dann speziell Filtern kann.
Ja habe ich gerade auch gesehen. Kenne das nur von NTFY. Wäre das trotzdem integrierbar um es auch ohne Filter sehen zu können?

> Punkt 2 ich kann den Titel natürlich noch als separate Zeile ausgeben.
Wäre vlt ne Idee für lange Texte. Ich kann den Titel auch rauskürzen.

> Das ist nen Bug unter iOS, normalerweise aktualisiert der das und es wird wieder mit Punkten angezeigt
Ok danke für die Info 👍

**Comment by androidseb25** [comment]
Ich setze alles mal auf die ToDo Liste

**Comment by androidseb25** [comment]
Punkt 1 & 2 sind im nächsten Update enthalten
