### ISSUE TITLE
Question: Is it a 1:1 relation between iGotify container and iOS device?

### ISSUE THREAD

**Issue by cmonty14** [androidseb25/iGotify-Notification-Assistent#60]
Hello,
can you please advise how to use multiple iOS devices with this container?
Is it a 1:1 relation between iGotify container and iOS device, means I need a dedicated container for each iOS device?

THX

**Comment by androidseb25** [comment]
No it's a 1:n relation.
The only thing is that the igotify need to reach the gotify websocket

**Comment by androidseb25** [comment]
you can add multiple gotify instances in one iGotify container, that can hold multiple iOS/iPadOS devices

**Comment by androidseb25** [comment]
In the latest version of the container you didn't need the environment variable anymore 

Please take a look at the release notes of 1.2.0.0

https://github.com/androidseb25/iGotify-Notification-Assistent/releases/tag/v1.2.0.0
