### ISSUE TITLE
[FEATURE REQUEST] Add the use of contact picture for notifications

### ISSUE THREAD

**Issue by cyrilschreiber3** [androidseb25/iGotify-Notification-Assistent#64]
I know that since IOS 15, apps can display the profile picture of the sender in the notification. 
Example from a Slack notification:
![image](https://github.com/androidseb25/iGotify-Notification-Assistent/assets/71042995/2e92776d-8487-40be-a925-1ad071e4cc5b)

Would it be possible to add this feature to iGotify ? It could display the icon of the app that send the notification.

**Comment by androidseb25** [comment]
I make some research for that

**Comment by androidseb25** [comment]
Research

- https://gist.github.com/Dexwell/dedef7389eae26c5b9db927dc5588905

**Comment by androidseb25** [comment]
- add appid or application image name to payload, for showing it
- first local test doesn't show any image on emulator
- next step trying on real device

**Comment by androidseb25** [comment]
feature coming with update 1.3 and container version 1.3.0.0

![Bildschirmfoto 2024-06-05 um 20 17 35](https://github.com/androidseb25/iGotify-Notification-Assistent/assets/11179091/33d059fc-ce3e-4345-9f39-43f491fd8dc3)

**Comment by androidseb25** [comment]
release 1.3 in review

**Comment by androidseb25** [comment]
App is now live
