### ISSUE TITLE
[BUG] Iphone error You need to provide a valid access token or user credentials to access this app.

### ISSUE THREAD

**Issue by ramstein74** [androidseb25/iGotify-Notification-Assistent#66]
When in my iphone entering gotify and igotify url i can move to the next screen.
Then i get asked the login credentials
I enter admin and admin because its the default and in my docker compose i didnt change it.
However i get the error You need to provide a valid access token or user credentials to access this app.
there is no input field for token.
Also what is the use of the instance name at the top ?
does that instance name is related to app names in the container gotify?

**Smartphone :**
 - Device: [e.g. iPhone13 mini]
 - OS: [e.g. iOS17]
 - Version of Container [e.g. 2.4.0]
 - Version of iGotify [e.g. 1.2.0.3]

**Comment by androidseb25** [comment]
Hi,

the login credentials admin/admin are the defaults of gotify when you didn't set it in the compose file 

`GOTIFY_DEFAULTUSER_PASS:  'my-very-strong-password'   # Change me!!!!! `

This part set the admin password for you.

The instance name is for organize when you use more then one user or gotify instance.

**Comment by ramstein74** [comment]
> Hi,
> 
> the login credentials admin/admin are the defaults of gotify when you didn't set it in the compose file
> 
> `GOTIFY_DEFAULTUSER_PASS: 'my-very-strong-password' # Change me!!!!! `
> 
> This part set the admin password for you.
> 
> The instance name is for organize when you use more then one user or gotify instance.

Yet dont see why i get the error

**Comment by ramstein74** [comment]
Just did that.
I create another user and with that new user still get the same error after
entering in credentials.
Also i switched that user "administrator rights" and still no success.
I already updated my iphone to 17.5 and still same error.

thank you

Em qua., 5 de jun. de 2024 às 17:38, Sebastian ***@***.***>
escreveu:

**Comment by androidseb25** [comment]
Can you please send me you're docker compose file you're problem is now very strange

**Comment by androidseb25** [comment]
and please provide me a screenshot with the message

**Comment by ramstein74** [comment]
[image: image.png]

Em qua., 5 de jun. de 2024 às 17:54, Sebastian ***@***.***>
escreveu:

**Comment by ramstein74** [comment]
> and please provide me a screenshot with the message

here it is. the password was written altough it does not show in the pic.
![image (6)](https://github.com/androidseb25/iGotify-Notification-Assistent/assets/1210858/43f131c0-d44a-483d-9c30-d44bb24ca664)

**Comment by androidseb25** [comment]
i found you're problem it's not one with the app only with you're config setup for the app.

Please try to use `https` instead of the `http` toggles

**Comment by ramstein74** [comment]
Solved thank you.
That was would not be possible without you.


Em qua., 5 de jun. de 2024 às 18:23, Sebastian ***@***.***>
escreveu:

**Comment by androidseb25** [comment]
no problems, have a nice day
