### ISSUE TITLE
Push notification after iPhone goes online

### ISSUE THREAD

**Issue by phoenix1184** [androidseb25/iGotify-Notification-Assistent#67]
First, thanks for your work. I appreciate it realy. 

I have an iPhone 15. 
Most of my notifications comes in at night but then my phone is offline. Netxt mornig I reconect my phone to Internet. All notifications are available on gotify, but there is no push notification on my phone. If phone is online when notifications happen, everything works like expected. 

Before you changed to secntfy, push notifications came when phone goes online again.
It would be great, if that feature would be possible to implement in future.

**Comment by androidseb25** [comment]
Hi, it's not a feature it's the APN service from apple that work so, I only transmit the message to the apple service and they hold it so long they want on there servers until device is online...

Maybe the reason of that is the encryption of the message and they can't read it and analyze the messages... 

I don't know it's not my part sorry

**Comment by phoenix1184** [comment]
Just thinking loud after some research, maybe you already doing it:

https://developer.apple.com/documentation/usernotifications/sending-notification-requests-to-apns 

apns-expiration

May this be a possible solution?

**Comment by androidseb25** [comment]
Ok I will take a look later if I set this parameter.

**Comment by androidseb25** [comment]
so I updated now the API. The expiration time is now set to 3 days (before it was 1 day)
I hope it works
