### ISSUE TITLE
[BUG] Login failed after a week

### ISSUE THREAD

**Issue by SandraCHC** [androidseb25/iGotify-Notification-Assistent#68]
One week iGotify and Gotify works like a charm.
But since yesterday, I can't login in the App or the Web GUI, and all tokens are invalid.

If I try to login, I see this log entry
```
Error #01: you need to provide a valid access token or user credentials to access this api
```

I don't see any error or changes. Do you have any idea what could have happened or how I could fix it without reinstalling?

**Comment by androidseb25** [comment]
That seems Like you have restarted the gotify Container and didn't Provide him an storage path where he can save his data. 

And a small hint it's Not an iGotify problem it's an Gotify problem (different developers)

**Comment by SandraCHC** [comment]
Oh yes. Sorry :) Thank you. Thats it
