### ISSUE TITLE
Alles löschen und Bilder senden

### ISSUE THREAD

**Issue by achbie** [androidseb25/iGotify-Notification-Assistent#7]
Hi
Danke für deine Arbeit. Bei mir läuft es gut auf verschiedenen Geräten (iPhone 12, iPad Air). 

1. Es wäre schön wenn man Nachrichten durch seitliches Wischen auch löschen kann. 
2. Einen Knopf zum löschen aller Nachrichten (Ähnlich der Web-GUI von gotify)
3. Ist es auch möglich Bilder mit der Nachricht zu verschicken? Also Nachricht mit Anhang.

**Comment by androidseb25** [comment]
> Hi
> 
> Danke für deine Arbeit. Bei mir läuft es gut auf verschiedenen Geräten (iPhone 12, iPad Air). 
> 
> 
> 
> 1. Es wäre schön wenn man Nachrichten durch seitliches Wischen auch löschen kann. 
> 
> 2. Einen Knopf zum löschen aller Nachrichten (Ähnlich der Web-GUI von gotify)
> 
> 3. Ist es auch möglich Bilder mit der Nachricht zu verschicken? Also Nachricht mit Anhang. 
> 
> 
> 
> 
Hi zu deinen 3 Punkten hier die Antwort: 


Punkt 1: Hab ich probiert vorher schon einzubauen, momentan leider nicht möglich umzusetzen. Werde es aber später nochmal probieren.

Punkt 2: Wird wahrscheinlich mit einem späteren Update kommen.

Punkt 3: wird nicht in die App Einzug erhalten da in der Weboberfläche auch nicht enthalten.

**Comment by achbie** [comment]
Danke für die schnelle Antwort. Schade mit den Bildern. Mit der AndroidApp scheint es möglich zu sein.

**Comment by androidseb25** [comment]
Punk 2 kommt im Update 1.0.5

**Comment by thethink3r** [comment]
> Danke für die schnelle Antwort. Schade mit den Bildern. Mit der AndroidApp scheint es möglich zu sein.

Bilder direkt einbetten ist auch mit der Android App nicht möglich. 
Du kannst dir Markdown formatierten Text senden, welcher dann z.B. eine URL zum Bild beinhaltet.

iGotify zeigt diese dann auch entsprechend wie die Android App an.

**Comment by androidseb25** [comment]
Punkt 1 ist mit dem aktuellen design nicht möglich deswegen schließe ich das ticket jetzt
