### ISSUE TITLE
[BUG] Updating App.

### ISSUE THREAD

**Issue by nicklutt** [androidseb25/iGotify-Notification-Assistent#72]
**Describe the bug**
After updating to v1.30 my app show this: 
![IMG_58851B615385-1](https://github.com/androidseb25/iGotify-Notification-Assistent/assets/139862644/37edb034-ebf6-4ff8-9af6-e0b1b1d476cd)

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone14]
 - OS: [e.g. iOS17.1]
 - Version of Container [latest]
 - Version of iGotify [1.30]

The button updated and continue doesnt fix the issue ;) 

**steps i already tried**
Removed APP and reinstall
Removed container and redeployed with latest tag and pull

**Comment by androidseb25** [comment]
Hot fix is coming, when still appears retry the Action

**Comment by androidseb25** [comment]
Update is accepted and live

**Comment by nicklutt** [comment]
Installed new version, but still same error.

**Comment by androidseb25** [comment]
Really ? I tried it many times and it works 🧐 (sims & real devices)

**Comment by pr0xyzer** [comment]
I reinstalled the app and recreated the containers, but it still remains stuck on updating.

**Comment by androidseb25** [comment]
@all please answer me this question, so I can find out why it happend.

did you've checked that the correct Container Version is Running?

Did you setuped a local instance (toogle Switch on)?

Is the Upgrade prompt directly?

**Comment by cyrilschreiber3** [comment]
It's the first screen that I see when I open the app so I can't change any setting.

Event with the container shut down I get the prompt

**Comment by androidseb25** [comment]
@DonPablo1010 says in issue #73

> Fix works on one device / instance where i left the app as it was. On another device / instance where i deleted the app on ios and reinstalled it, the app stills hangs on the blue screen where it can't find a latest version instance. I'm not able to reenter the urls etc. of gotify and igotify...

**Comment by yeyeoke** [comment]
Yeah sadly this didn't solve anything for me either, it still hangs on this screen even after reinstalling the app and rebooting the phone.

**Comment by Reginard** [comment]
> Yeah sadly this didn't solve anything for me either, it still hangs on this screen even after reinstalling the app and rebooting the phone.

Same here

**Comment by kallemarc** [comment]
Gleiches Problem, ich hatte keine Push Benachrichtigungen mehr bekommen, nachdem ich meinen Server neu aufsetzt habe, daher habe ich die Instanz aus der App gelöscht bevor ich die App gelöscht habe, jetzt habe ich die App neugeladen und bekomme die gleiche Fehlermeldung.

Same problem, I had stopped getting push notifications after I reset my server, so I deleted the instance from the app before I deleted the app, now I have reloaded the app and get the same error message.

**Comment by androidseb25** [comment]
I think I have found the issue,
It's the `if else` statement that's broken. I will fix it today, I'm currently on an meeting.

**Comment by androidseb25** [comment]
Update approved and now it goes live

**Comment by pr0xyzer** [comment]
Installed, and now everything works! Thank you very much.

**Comment by Reginard** [comment]
Working again, many thanks
