### ISSUE TITLE
[BUG] No Push Notifications After Reinstalling Docker Container

### ISSUE THREAD

**Issue by kallemarc** [androidseb25/iGotify-Notification-Assistent#74]
Beschreibung des Fehlers:
Es werden keine Push-Benachrichtigungen gesendet. Der Docker-Container wurde neu aufgesetzt, einschließlich der Bereinigung von Volumes und anderen Daten.

Erwartetes Verhalten:
Es sollte eine Push-Benachrichtigung gesendet werden.

Description of the Error:
No push notifications are being sent. The Docker container was reinstalled, including the clearing of volumes and other data.

Expected Behavior:
A push notification should be sent.

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro
 - OS: 17.5.1
 - Version of Container API 1.3.0.0
 - Version of iGotify 2.5.0

**Additional context**

19:13:00.144 INFO Logger.getInstance():30 - ♻️ - Initialize iGotify Logger

19:13:00.153 INFO SecNtfy.initialize():67 - ♻️ - API URL https://api.secntfy.app

19:13:00.157 INFO SecNtfy.initialize():68 - ♻️ - Bundle Group group.sr.iGotify

19:13:00.213 INFO SecNtfy.initialize():79 - PubKey: MIIBCgKCAQEAp13Cnw3d5DP1GxZh6UePjFE4J1yyltTLVZxzE5GRBAaxnu7LW40VKRjZ289yxuYPFeDtSCAIJ2n2VxLtK02MNi17uIXIumavMvjOLVRQEVbm8fJ+TaeemuYnZ8vM+qOZdy8H0PUsQQW8e7fzHKIhL5lFxyZZ8EiWhBomKKl/LMtobmnr4WnP6yfHlLOzwb8gK+u3Zp+4k4rrEmcPf/ouivBTY869fdU1RR7rP4OGyggLTagEwgNdYb43muvz0glh7BEduhS2X+F999YLLoLaP3RJzE3IhA1XM2FBL8VrP1zl25j3HauDpeZ81VOA9QgasqgNMr+E+Q6j0U0jCt5DZQIDAQAB

19:13:00.218 INFO SecNtfy.initialize():80 - PrivKey: MIIEo*****oSRQi

19:13:00.221 INFO SecNtfy.configure():104 - Model: iPhone 14 Pro

19:13:00.226 INFO SecNtfy.configure():105 - OS: 17.5.1

19:13:00.233 INFO SecNtfy.configure():107 - PubKey: MIIBCgKCAQEAp13Cnw3d5DP1GxZh6UePjFE4J1yyltTLVZxzE5GRBAaxnu7LW40VKRjZ289yxuYPFeDtSCAIJ2n2VxLtK02MNi17uIXIumavMvjOLVRQEVbm8fJ+TaeemuYnZ8vM+qOZdy8H0PUsQQW8e7fzHKIhL5lFxyZZ8EiWhBomKKl/LMtobmnr4WnP6yfHlLOzwb8gK+u3Zp+4k4rrEmcPf/ouivBTY869fdU1RR7rP4OGyggLTagEwgNdYb43muvz0glh7BEduhS2X+F999YLLoLaP3RJzE3IhA1XM2FBL8VrP1zl25j3HauDpeZ81VOA9QgasqgNMr+E+Q6j0U0jCt5DZQIDAQAB

19:13:00.237 INFO SecNtfy.configure():108 - PrivKey: MIIEo*****oSRQi

19:13:00.294 VERBOSE AppDelegate.application():84 - APNs token retrieved: 32 bytes

19:13:00.296 VERBOSE AppDelegate.application():87 - The token: E2745*****ACF70

19:13:00.298 INFO SecNtfy.setApnsToken():141 - E2745*****ACF70

19:13:46.362 INFO SecNtfy.getInstance():43 - ♻️ - instance init

19:13:46.777 INFO SecNtfy.PostDevice():171 - ♻️ - Device successfully created! NTFY-DEVICE-CYTYLsOb8e9cEARIrsGbeOvUfSIghpt1ucsRRbFGFEgG5P3vtavyQ

19:13:48.388 INFO SecNtfy.getInstance():43 - ♻️ - instance init

19:13:48.475 INFO SecNtfy.PostDevice():171 - ♻️ - Device already added NTFY-DEVICE-CYTYLsOb8e9cEARIrsGbeOvUfSIghpt1ucsRRbFGFEgG5P3vtavyQ

19:13:48.479 VERBOSE Functions.sendTokenToSecNtfy():222 - registration token: NTFY-DEVICE-CYTYLsOb8e9cEARIrsGbeOvUfSIghpt1ucsRRbFGFEgG5P3vtavyQ

19:14:19.474 INFO Logger.getInstance():30 - ♻️ - Initialize iGotify Logger

19:14:19.485 INFO SecNtfy.initialize():67 - ♻️ - API URL https://api.secntfy.app

19:14:19.492 INFO SecNtfy.initialize():68 - ♻️ - Bundle Group group.sr.iGotify

19:14:19.496 INFO SecNtfy.initialize():79 - PubKey: MIIBCgKCAQEAp13Cnw3d5DP1GxZh6UePjFE4J1yyltTLVZxzE5GRBAaxnu7LW40VKRjZ289yxuYPFeDtSCAIJ2n2VxLtK02MNi17uIXIumavMvjOLVRQEVbm8fJ+TaeemuYnZ8vM+qOZdy8H0PUsQQW8e7fzHKIhL5lFxyZZ8EiWhBomKKl/LMtobmnr4WnP6yfHlLOzwb8gK+u3Zp+4k4rrEmcPf/ouivBTY869fdU1RR7rP4OGyggLTagEwgNdYb43muvz0glh7BEduhS2X+F999YLLoLaP3RJzE3IhA1XM2FBL8VrP1zl25j3HauDpeZ81VOA9QgasqgNMr+E+Q6j0U0jCt5DZQIDAQAB

19:14:19.503 INFO SecNtfy.initialize():80 - PrivKey: MIIEo*****oSRQi

19:14:19.507 INFO SecNtfy.configure():104 - Model: iPhone 14 Pro

19:14:19.511 INFO SecNtfy.configure():105 - OS: 17.5.1

19:14:19.515 INFO SecNtfy.configure():107 - PubKey: MIIBCgKCAQEAp13Cnw3d5DP1GxZh6UePjFE4J1yyltTLVZxzE5GRBAaxnu7LW40VKRjZ289yxuYPFeDtSCAIJ2n2VxLtK02MNi17uIXIumavMvjOLVRQEVbm8fJ+TaeemuYnZ8vM+qOZdy8H0PUsQQW8e7fzHKIhL5lFxyZZ8EiWhBomKKl/LMtobmnr4WnP6yfHlLOzwb8gK+u3Zp+4k4rrEmcPf/ouivBTY869fdU1RR7rP4OGyggLTagEwgNdYb43muvz0glh7BEduhS2X+F999YLLoLaP3RJzE3IhA1XM2FBL8VrP1zl25j3HauDpeZ81VOA9QgasqgNMr+E+Q6j0U0jCt5DZQIDAQAB

19:14:19.520 INFO SecNtfy.configure():108 - PrivKey: MIIEo*****oSRQi

19:14:19.615 VERBOSE AppDelegate.application():84 - APNs token retrieved: 32 bytes

19:14:19.618 VERBOSE AppDelegate.application():87 - The token: E2745*****ACF70

19:14:19.621 INFO SecNtfy.setApnsToken():141 - E2745*****ACF70

19:14:21.072 INFO SecNtfy.getInstance():43 - ♻️ - instance init

19:14:21.243 INFO SecNtfy.PostDevice():171 - ♻️ - Device already added NTFY-DEVICE-CYTYLsOb8e9cEARIrsGbeOvUfSIghpt1ucsRRbFGFEgG5P3vtavyQ

19:14:21.254 VERBOSE Functions.sendTokenToSecNtfy():222 - registration token: NTFY-DEVICE-CYTYLsOb8e9cEARIrsGbeOvUfSIghpt1ucsRRbFGFEgG5P3vtavyQ

19:14:21.286 VERBOSE Functions.sendTokenToSecNtfy():232 - result: Fehler beim hinzugefügen des Gerätes! Successful: false Token: NTFY-DEVICE-CYTYLsOb8e9cEARIrsGbeOvUfSIghpt1ucsRRbFGFEgG5P3vtavyQ

**Comment by androidseb25** [comment]
Hi was passiert wenn du deine iGotify URL öffnest und beim Punkt (siehe Bild) das Benachrichtigungstoken einfügst (Einstellungen-> Benachrichtigungstoken NTFY-DEVICE-XXXX) und auf execute drückst kommt dann eine Notification?

Wenn ja, bitte zeig mir mal was dein iGotify Container log sagt.

**Comment by androidseb25** [comment]
![image](https://github.com/androidseb25/iGotify-Notification-Assistent/assets/11179091/288907e1-c52f-4309-9fca-66d02315b705)

**Comment by kallemarc** [comment]
Die Benachrichtigung kam.

gotify   | 2024-07-10T17:28:20Z | 400 |     328.567µs |      172.23.0.1 | GET      "/stream?token=[masked]"
gotify   | Error #01: websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header
igotify  | Disconnection happened, type: Error
igotify  | Webseocket Reconnection failed with Error. Try to reconnect in 10s.
igotify  | info: Microsoft.Hosting.Lifetime[14]
igotify  |       Now listening on: http://[::]:8080
igotify  | info: Microsoft.Hosting.Lifetime[0]
igotify  |       Application started. Press Ctrl+C to shut down.
igotify  | info: Microsoft.Hosting.Lifetime[0]
igotify  |       Hosting environment: Production
igotify  | info: Microsoft.Hosting.Lifetime[0]
igotify  |       Content root path: /app
igotify  | warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
igotify  |       Failed to determine the https port for redirect.
igotify  | WxqRSJqPDlw3HxtqukNHOgeqObkdqAf7fF+/q/LWCEqosdH2NWh665lFjm3LjUlNYolOP4FYceYv33TTkpISId+7xf3Emwd2fcfWRxH3TfcTZidY3DkJux1zBB7cKYDJy93FrvS3BVbRp3JCmL5CIhX4wCRw/cQnY59kvbwC7r8h+OfbWmJfF1K8zURbWmWf/uYHnHGYg1zJl01AGCU/d9bB3QuET3uK3mGvoIaGutpl1UkLHFyayIOpVsb9KJFW7MhnxUF4NB3ApvxumxRX0P63ZxJke2OI4GZFGHfPtu1fKb+owj7B3H1XudDuRO3YWqfQImYJcE32aLnEuLNcbQ==
igotify  | WxqRSJqPDlw3HxtqukNHOgeqObkdqAf7fF+/q/LWCEqosdH2NWh665lFjm3LjUlNYolOP4FYceYv33TTkpISId+7xf3Emwd2fcfWRxH3TfcTZidY3DkJux1zBB7cKYDJy93FrvS3BVbRp3JCmL5CIhX4wCRw/cQnY59kvbwC7r8h+OfbWmJfF1K8zURbWmWf/uYHnHGYg1zJl01AGCU/d9bB3QuET3uK3mGvoIaGutpl1UkLHFyayIOpVsb9KJFW7MhnxUF4NB3ApvxumxRX0P63ZxJke2OI4GZFGHfPtu1fKb+owj7B3H1XudDuRO3YWqfQImYJcE32aLnEuLNcbQ==
gotify   | 2024-07-10T17:28:30Z | 400 |     296.874µs |      172.23.0.1 | GET      "/stream?token=[masked]"
gotify   | Error #01: websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header
igotify  | Disconnection happened, type: Error
igotify  | Webseocket Reconnection failed with Error. Try to reconnect in 10s.
gotify   | 2024-07-10T17:28:40Z | 400 |      273.11µs |      172.23.0.1 | GET      "/stream?token=[masked]"
gotify   | Error #01: websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header
igotify  | Disconnection happened, type: Error
igotify  | Webseocket Reconnection failed with Error. Try to reconnect in 10s.

**Comment by androidseb25** [comment]
ok also ist es so wie der log sagt nen problem mit dem websocket bei dir.

Wie nutzt du den iGotify Assistent? So wie es aussieht als service richtig

**Comment by kallemarc** [comment]
Ich habe durch dein Hinweis den Fehler gefunden.

In der vHost folgende hinzugefügt:
    RewriteCond %{HTTP:Upgrade} =websocket [NC]
    RewriteCond %{HTTP:Connection} upgrade [NC]
    RewriteRule /(.*) ws://localhost:PORT/$1 [P,L]

und es geht wieder, wundert mich nur das es vorher ging.

**Comment by androidseb25** [comment]
Ok alles klar 😅
Freut mich das es wieder funktioniert
