### ISSUE TITLE
Push-Benachrichtigung für unterschiedliche Benutzer funktioniert nicht

### ISSUE THREAD

**Issue by dannnick** [androidseb25/iGotify-Notification-Assistent#8]
Hallo, 

mir ist aufgefallen, dass die Push-Benachrichtigung nicht für die unterschiedliche Benutzer nicht funktioniert. 

Ich habe eine App erstellt für jeden einzelnen Benutzer und die Benutzer dann in der iOS-App angemeldet und es kommt keine Push-Benachrichtigung. 
Wenn ich dann in die App rein gehe, erscheinen die Nachrichten. 

Mir ist auch aufgefallen, wenn ich eine App mit dem admin-Nutzer erstelle und dorthin ein curl POST sende, dann bekommt wirklich jedes iPhone eine Push-Benachrichtigung (obwohl die nicht als admin eingeloggt sind), die in der App aber nicht angezeigt wird. 

Mache ich hier was falsch?

Danke!

**Comment by androidseb25** [comment]
Hi,
es gibt kein Multiuser Support für die App, da der Websocket nur **ein Client von einem User** unterstützt (das ist das Client Token in der docker compose). Der User dem dieses Client Token gehört (zb. Admin) bekommt auch die Benachrichtigung solange das Benachrichtigungstoken hinterlegt ist! 

Grüße Seb

**Comment by androidseb25** [comment]
eine woche keine Antwort also erledigt
