### ISSUE TITLE
[FEATURE REQUEST] No Notification Option

### ISSUE THREAD

**Issue by Nollknolle** [androidseb25/iGotify-Notification-Assistent#80]
**Is your feature request related to a problem? Please describe.**

Es gibt Nachrichten die viel kommen, Pings, Update Nachrichten, etc. Solche Nachrichten möchte man zwar in der App nachlesen können, aber vielleicht nicht jedes Mal als Push Nachricht bekommen.

**Describe the solution you'd like**
Die Möglichkeit einstellen zu können, dass zum Beispiel bei Level 0 die Nachricht in der App angezeigt wird, aber er keine Push Nachricht schickt. Nur als Anzeige in der App.

**Comment by androidseb25** [comment]
Coole Idee, danke.
Wird bestimmt mit dem 1.4 Update und iOS 18 kommen :)

**Comment by androidseb25** [comment]
wird im Update 1 vorhanden sein, gerade in den internen Beta Tests
