### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by thomasvoni** [androidseb25/iGotify-Notification-Assistent#81]
Zeitstempel der Mitteilungen stimmen seit dem letzten Update nicht mehr. Es wird immer die aktuelle Zeit angezeigt, nicht die Zeit wo die Nachricht empfangen wurde.

App Version 1.3.2(25)
Server Version 2.5.0
API Server Version 1.3.0.0

iPhone und iPad

**Comment by androidseb25** [comment]
Hi les dir mal die Release notes durch, es stand auch so in der App


https://github.com/androidseb25/iGotify-Notification-Assistent/releases/tag/v1.3.0.0

**Comment by thomasvoni** [comment]
Ok sorry, mein Fehler - das habe ich übersehen 😳
Danke fürs rasche feedback!
