### ISSUE TITLE
Was fixed but now appears again!!😱

### ISSUE THREAD

**Issue by DonPablo1010** [androidseb25/iGotify-Notification-Assistent#83]
Was fixed but now appears again!!😱

![IMG_9184](https://github.com/user-attachments/assets/0a95cfa3-c587-413c-b741-81dbb2e52399)

_Originally posted by @DonPablo1010 in https://github.com/androidseb25/iGotify-Notification-Assistent/issues/82#issuecomment-2226270165_

**Comment by DonPablo1010** [comment]
Now it works again and the error message is gone... Don't see anything related in the container logs...🤷🏼‍♂️

**Comment by androidseb25** [comment]
It's probably the a nameserver in you're near that didn't updated yet it can be take up to 24h :/

**Comment by androidseb25** [comment]
But it's fixed:)
