### ISSUE TITLE
Datum und Uhrzeit der Mitteilung ist immer aktuelle Zeit

### ISSUE THREAD

**Issue by Undetected-Treasure** [androidseb25/iGotify-Notification-Assistent#85]
Vielen Dank für Deine tolle Arbeit. Mir ist etwas aufgefallen.
Man kann (zumindest bei mir) nicht sehen wann die Mitteilung gekommen, bzw. die Nachricht ausgelöst wurde. Jede Nachricht die ich bekomme trägt die aktuelle Zeit, sprich man sieht immer das Datum und die Zeit die gerade ist wenn man die Nachricht öffnet. Da ich Nachts aber nur extrem kritische Nachrichten tatsächlich mit Ton empfange und alle anderen lautlos, weiß ich bei den lautlosen nicht genau wann das Problem aufgetreten ist, dazu muss ich dann im direkt in Uptime Kuma. Kann man das noch anpassen?  Das wäre super, Danke. Gruß Olaf

**Comment by androidseb25** [comment]
Hi Olaf, hast du wie im letzten Changelog beschrieben die Environment variable mit der Zeitzone gelöscht?

Es gab da nämlich ein Bug

**Comment by Undetected-Treasure** [comment]
Moin Sebastian,
hatte ich nicht gelesen. Habe die Zeitzone gelöscht und es passt jetzt. Danke für die schnelle Rückmeldung.
Schönes WE

**Comment by androidseb25** [comment]
Kein Problem und gern geschehen.
