### ISSUE TITLE
Error igotify  | Disconnection happened, type: Error igotify  | Webseocket Reconnection failed with Error. Try to reconnect in 10s.

### ISSUE THREAD

**Issue by fvargasfrank** [androidseb25/iGotify-Notification-Assistent#87]
Latest ios 17 
iphone 15 pro 

Hello would you be able to help me igotify working ?
all i see are these error 

igotify  | Disconnection happened, type: Error
igotify  | Webseocket Reconnection failed with Error. Try to reconnect in 10s.
igotify  | Disconnection happened, type: Error
igotify  | Webseocket Reconnection failed with Error. Try to reconnect in 10s.

and 

gotify  | 2024-08-04T20:1808-04:00 | 400 |    1.186004ms |   192.168.1.153 | GET      "/stream?token=[masked]"
gotify  | Error #01: websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header
gotify  | 2024-08-04T20:1818-04:00 | 400 |     190.093µs |   192.168.1.153 | GET      "/stream?token=[masked]"
gotify  | Error #01: websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header

I am able to login successfully in the app no error

**Comment by fvargasfrank** [comment]
![IMG_0389](https://github.com/user-attachments/assets/a6e9f55c-1d2f-4112-8456-b7638673828a)

**Comment by androidseb25** [comment]
you can write me also on Discord, i accept the request

**Comment by benniblot** [comment]
What was the solution?

**Comment by androidseb25** [comment]
He fixed it by his self 

Can I help you?
