### ISSUE TITLE
[BUG] Timestamps incorrect

### ISSUE THREAD

**Issue by sebseb83** [androidseb25/iGotify-Notification-Assistent#88]
**Describe the bug**
Timestamps for any notifications always show latest time and not when events occurred. 

**Expected behavior**
Timestamps show correct times.

![IMG_2705](https://github.com/user-attachments/assets/e09f2b01-9c0b-470f-8976-b30bd3c650d5)

Using iPhone 15 plus. On iOS 15 beta but happened when I was still on stable build. 

Noticed issue happening after last iGotify update. Cheers. Love your work. Also your buy me a drink link doesn’t do anything in the app. Still managed to donate but thought you may like to know clicking it doesn’t do anything.

**Comment by androidseb25** [comment]
Please read the changelog did you deleted the TZ Environment in the docker compose yaml?

**Comment by sebseb83** [comment]
My apologies, that worked, thank you.
