### ISSUE TITLE
[BUG] not getting push notifications

### ISSUE THREAD

**Issue by uotw** [androidseb25/iGotify-Notification-Assistent#89]
**Describe the bug**
iOS App not getting push notifications.  When a message is posted to the Gotify server I have manually refresh the messages on iGotify for them to show up.

**Expected behavior**
I expect that when a message is posted to the Gotify server that iGotify will push a notification to my iPhone. 

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro Max
 - OS: iOS17.5.1
 - Version of iGotify 1.3.2 (25)

**Comment by androidseb25** [comment]
Please take a look at the closed issues with that problem, when you didn't find something provide me some logs from the app and the docker container!

**Comment by uotw** [comment]
Ah, another case where I didn't properly read the manual. Followed the docker installation instructions and everything's working well now. Cheers!

I did find one actual bug - when I went to 'buy you a cool drink' in the iOS app the button never fully loads. Do you have a venmo?

**Comment by androidseb25** [comment]
Ok cool 

Normally it's works, but you find here on GitHub a PayPal link

**Comment by androidseb25** [comment]
Thx for the donation 😇
