### ISSUE TITLE
[BUG]  Timestamp  of iGotfy is always 0s ago

### ISSUE THREAD

**Issue by Bra-Ger** [androidseb25/iGotify-Notification-Assistent#90]
**Describe the bug**
Notify & iGotify are working fine only the time of the message is always 0s ago (see picture)

**Expected behavior**
The time should change 

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro Max
 - OS: 17.6.1
 - app version 1.3.2 (25)
 - Server version 2.5.0
 - API version 1.3.0.0
- running in docker on an Unraid system.

**Additional context**
-I am using cloudflare. ( issue exists with local IPs too)
-The log files have correct timestamps.
 
![IMG_0383](https://github.com/user-attachments/assets/11fe9fc7-bf81-4ad6-b41f-86d1ccbc5b16)

**Comment by androidseb25** [comment]
Hi did you take a look at some closed issues #88 #86 for example?

You need to remove the TZ Variable from the container. This change stands in the latest changelog of the App and the container release!

**Comment by Bra-Ger** [comment]
Hello,
Thank you for your fast reply. 

Gotify needs TZ=UTC  as timezone if you are using Unraid.

Thank you for the hint. This bug can be closed.

**Comment by DanielDeng3** [comment]
gotity and igotity  TZ env all need to delete

> i have same issue, if you use unraid you can use portainer to edit env,and delete TZ. then deploy again. it's works for me
