### ISSUE TITLE
[FEATURE REQUEST] App Name in Notification

### ISSUE THREAD

**Issue by Nollknolle** [androidseb25/iGotify-Notification-Assistent#92]
**Is your feature request related to a problem? Please describe.**
Ich habe mehrere Apps und das Problem wenn ich meine Apple Watch an habe das ich nicht sehe von welcher App die Nachricht nun kam. Auch am iPhone wird es nicht gezeigt.

**Describe the solution you'd like**
Anzeige des Gotify-App Namens in der Notification. Eventuell in den Einstellungen aktivierbar.

**Describe alternatives you've considered**
none

**Additional context**
![image](https://github.com/user-attachments/assets/0787f500-ed25-4259-a964-2632536888c8)

**Comment by androidseb25** [comment]
Feature added in the latest beta build

![IMG_2692](https://github.com/user-attachments/assets/cee8e119-dda6-4e4d-9995-0330fdb429d6)
![IMG_2693](https://github.com/user-attachments/assets/badcdd47-8d96-4690-825a-2dcfcb457099)
![IMG_2694](https://github.com/user-attachments/assets/4c34bd9d-e84f-4696-bb02-957140efc03a)
