### ISSUE TITLE
[BUG] Unraid error:

### ISSUE THREAD

**Issue by ne0ark** [androidseb25/iGotify-Notification-Assistent#94]
![image](https://github.com/user-attachments/assets/352b8dac-809b-46dc-aafe-43b6f698cba8)

Please take a look above error. I can see notification in app but i am not getting any push notifications.

**Comment by androidseb25** [comment]
Yeah he is trying to connect to the websocket of gotify how did you configure the app?

**Comment by androidseb25** [comment]
Or did you have a deleted the required client token?

This error has several causes.

**Comment by androidseb25** [comment]
Ok, did you specified the correct url in the app? Because the app say the container which way he use

**Comment by androidseb25** [comment]
Ok, but this environment `  -e 'GOTIFY_URL'='http://192.168.1.200:8070' ` variable didn't exist anymore

**Comment by androidseb25** [comment]
Please take a look in the readme to configure you're compose correct

**Comment by androidseb25** [comment]
Sorry I don't know because I don't use unraid

**Comment by androidseb25** [comment]
Hi please read following issue for this reason

https://github.com/androidseb25/iGotify-Notification-Assistent/issues/59

**Comment by RichKidsDev** [comment]
I updated the template in unraid.

**Comment by RichKidsDev** [comment]
I noticed that once the database has been created and you change the entries for the variables, it has no effect. Only if you delete it and create a new one.

**Comment by androidseb25** [comment]
He change the entries only on restart of the container when he read the entries.

**Comment by androidseb25** [comment]
s this error still actually?

When no this Issue will be closed on day 30.
